/*** Object: StoredProcedure [Erp].[_ZFW_LaborLaborDtl_GetBySysRowID] ******/

CREATE OR ALTER PROCEDURE [Erp].[_ZFW_LaborLaborDtl_GetBySysRowID]
	@SysRowID uniqueidentifier = null
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
---------------------------------------------------------------------
-- SELECT for table LaborDtl AS LaborDtl / Table Number : 1
---------------------------------------------------------------------
SELECT [t0].[Company],
[t0].[EmployeeNum],
[t0].[LaborHedSeq],
[t0].[LaborDtlSeq],
[t0].[LaborType],
[t0].[LaborTypePseudo],
[t0].[ReWork],
[t0].[ReworkReasonCode],
[t0].[JobNum],
[t0].[AssemblySeq],
[t0].[OprSeq],
[t0].[JCDept],
[t0].[ResourceGrpID],
[t0].[OpCode],
[t0].[LaborHrs],
[t0].[BurdenHrs],
[t0].[LaborQty],
[t0].[ScrapQty],
[t0].[ScrapReasonCode],
[t0].[SetupPctComplete],
[t0].[Complete],
[t0].[IndirectCode],
[t0].[LaborNote],
[t0].[ExpenseCode],
[t0].[LaborCollection],
[t0].[AppliedToSchedule],
[t0].[ClockInMInute],
[t0].[ClockOutMinute],
[t0].[ClockInDate],
[t0].[ClockinTime],
[t0].[ClockOutTime],
[t0].[ActiveTrans],
[t0].[OverRidePayRate],
[t0].[LaborRate],
[t0].[BurdenRate],
[t0].[DspClockInTime],
[t0].[DspClockOutTime],
[t0].[ResourceID],
[t0].[OpComplete],
[t0].[EarnedHrs],
[t0].[AddedOper],
[t0].[PayrollDate],
[t0].[PostedToGL],
[t0].[FiscalYear],
[t0].[FiscalPeriod],
[t0].[JournalNum],
[t0].[GLTrans],
[t0].[JournalCode],
[t0].[InspectionPending],
[t0].[CallNum],
[t0].[CallLine],
[t0].[ServNum],
[t0].[ServCode],
[t0].[ResReasonCode],
[t0].[WipPosted],
[t0].[DiscrepQty],
[t0].[DiscrpRsnCode],
[t0].[ParentLaborDtlSeq],
[t0].[LaborEntryMethod],
[t0].[FiscalYearSuffix],
[t0].[FiscalCalendarID],
[t0].[BFLaborReq],
[t0].[ABTUID],
[t0].[ProjectID],
[t0].[PhaseID],
[t0].[RoleCd],
[t0].[TimeTypCd],
[t0].[PBInvNum],
[t0].[PMUID],
[t0].[TaskSetID],
[t0].[ApprovedDate],
[t0].[ClaimRef],
[t0].[QuickEntryCode],
[t0].[TimeStatus],
[t0].[CreatedBy],
[t0].[CreateDate],
[t0].[CreateTime],
[t0].[ChangedBy],
[t0].[ChangeDate],
[t0].[ChangeTime],
[t0].[ActiveTaskID],
[t0].[LastTaskID],
[t0].[CreatedViaTEWeekView],
[t0].[CurrentWFStageID],
[t0].[WFGroupID],
[t0].[WFComplete],
[t0].[ApprovalRequired],
[t0].[SubmittedBy],
[t0].[PBRateFrom],
[t0].[PBCurrencyCode],
[t0].[PBHours],
[t0].[PBChargeRate],
[t0].[PBChargeAmt],
[t0].[DocPBChargeRate],
[t0].[Rpt1PBChargeRate],
[t0].[Rpt2PBChargeRate],
[t0].[Rpt3PBChargeRate],
[t0].[DocPBChargeAmt],
[t0].[Rpt1PBChargeAmt],
[t0].[Rpt2PBChargeAmt],
[t0].[Rpt3PBChargeAmt],
[t0].[Shift],
[t0].[ActID],
[t0].[DtailID],
[t0].[ProjProcessed],
[t0].[AsOfDate],
[t0].[AsOfSeq],
[t0].[JDFInputFiles],
[t0].[JDFNumberOfPages],
[t0].[BatchWasSaved],
[t0].[AssignToBatch],
[t0].[BatchComplete],
[t0].[BatchRequestMove],
[t0].[BatchPrint],
[t0].[BatchLaborHrs],
[t0].[BatchPctOfTotHrs],
[t0].[BatchQty],
[t0].[BatchTotalExpectedHrs],
[t0].[JDFOpCompleted],
CAST([t0].[SysRevID] AS BigInt) AS SysRevID,
[t0].[SysRowID],
[t0].[Downtime],
[t0].[RefJobNum],
[t0].[RefAssemblySeq],
[t0].[RefOprSeq],
[t0].[Imported],
[t0].[ImportDate],
[t0].[TimeAutoSubmit],
[t0].[BatchMode],
[t0].[BillServiceRate],
[t0].[HCMPayHours],
[t0].[EpicorFSA],
[t0].[DiscrepAttributeSetID],
[t0].[LaborAttributeSetID],
[t0].[ScrapAttributeSetID],
[t0].[PCID],
[t0].[NonConfPCID],
CAST(1 AS bit) AS [AllowDirLbr],
'' AS [ApprovalPhaseDesc],
'' AS [ApprovalPhaseID],
'' AS [ApprovalProjectDesc],
'' AS [ApprovalProjectID],
'' AS [ApprovedBy],
CAST(0 AS bit) AS [ApprvrHasOpenTask],
'' AS [BaseCurrCodeDesc],
CAST(0.0 AS decimal(20,9)) AS [BurdenCost],
'' AS [CallCode],
'' AS [CapabilityDescription],
'' AS [CapabilityID],
CAST(0.0 AS decimal(20,9)) AS [ChargeRate],
'' AS [ChargeRateSRC],
'' AS [ChgRateCurrDesc],
CAST(0 AS bit) AS [CompleteFlag],
'' AS [ContractCode],
CAST(0 AS int) AS [ContractNum],
'' AS [DiscrepUOM],
CAST(0 AS bit) AS [DisLaborType],
'' AS [DisplayJob],
CAST(0 AS bit) AS [DisPrjRoleCd],
CAST(0 AS bit) AS [DisTimeTypCd],
CAST(0.0 AS decimal(20,9)) AS [DowntimeTotal],
'' AS [DspChangeTime],
'' AS [DspCreateTime],
'' AS [DspTotHours],
null AS [DtClockIn],
null AS [DtClockOut],
CAST(0.0 AS decimal(20,9)) AS [EfficiencyPercentage],
'' AS [EmployeeName],
CAST(0 AS bit) AS [EnableComplete],
CAST(0 AS bit) AS [EnableCopy],
CAST(0 AS bit) AS [EnableDiscrepQty],
CAST(0 AS bit) AS [EnableInspection],
CAST(0 AS bit) AS [EnableLaborQty],
CAST(0 AS bit) AS [EnableNextOprSeq],
CAST(0 AS bit) AS [EnablePrintTagsList],
CAST(0 AS bit) AS [EnableRecall],
CAST(0 AS bit) AS [EnableRecallAprv],
CAST(0 AS bit) AS [EnableRequestMove],
CAST(0 AS bit) AS [EnableResourceGrpID],
CAST(0 AS bit) AS [EnableScrapQty],
CAST(0 AS bit) AS [EnableSN],
CAST(0 AS bit) AS [EnableSubmit],
CAST(0 AS bit) AS [EndActivity],
CAST(0 AS bit) AS [EnteredOnCurPlant],
'' AS [FSAAction],
'' AS [FSACallCode],
'' AS [FSAContractCode],
CAST(0 AS int) AS [FSAContractNum],
'' AS [FSAEmpID],
CAST(0 AS int) AS [FSAEquipmentInstallID],
'' AS [FSAEquipmentPartNum],
CAST(0 AS int) AS [FSAServiceOrderNum],
CAST(0 AS int) AS [FSAServiceOrderResourceNum],
'' AS [FSAWarrantyCode],
CAST(0 AS bit) AS [FSComplete],
CAST(0.0 AS decimal(20,9)) AS [GLTranAmt],
null AS [GLTranDate],
CAST(1 AS bit) AS [HasAccessToRow],
CAST(0 AS bit) AS [HasComments],
CAST(0 AS bit) AS [HH],
'' AS [IntExternalKey],
CAST(0 AS bit) AS [ISFixHourAndQtyOnly],
CAST(0 AS bit) AS [JCSystReworkReasons],
CAST(0 AS bit) AS [JCSystScrapReasons],
CAST(0 AS bit) AS [JobOperComplete],
'' AS [JobType],
N'MFG' AS [JobTypeCode],
CAST(0.0 AS decimal(20,9)) AS [LaborCost],
'' AS [LaborUOM],
'' AS [LbrDay],
'' AS [LbrMonth],
'' AS [LbrWeek],
CAST(0 AS bit) AS [MES],
'' AS [MultipleEmployeesText],
CAST(0 AS int) AS [NewDifDateFlag],
'' AS [NewPrjRoleCd],
'' AS [NewRoleCdDesc],
CAST(0 AS int) AS [NextAssemblySeq],
'' AS [NextOperDesc],
CAST(0 AS int) AS [NextOprSeq],
'' AS [NextResourceDesc],
CAST(0 AS bit) AS [NonConfProcessed],
CAST(0 AS bit) AS [NotSubmitted],
CAST(0 AS bit) AS [OkToChangeResourceGrpID],
'' AS [PartDescription],
'' AS [PartNum],
CAST(0 AS bit) AS [PBAllowModify],
'' AS [PendingApprovalBy],
'' AS [PhaseJobNum],
CAST(0 AS int) AS [PhaseOprSeq],
CAST(0 AS bit) AS [PrintNCTag],
'' AS [PrjUsedTran],
'' AS [ProdDesc],
'' AS [ProjPhaseID],
CAST(0 AS bit) AS [RequestMove],
'' AS [ResourceDesc],
CAST(0 AS bit) AS [RoleCdDisplayAll],
'' AS [ScrapUOM],
CAST(0 AS bit) AS [SentFromMES],
CAST(0 AS bit) AS [StartActivity],
CAST(0 AS bit) AS [TimeDisableDelete],
CAST(0 AS bit) AS [TimeDisableUpdate],
'' AS [TreeNodeImageName],
CAST(0 AS bit) AS [UnapprovedFirstArt],
'' AS [WarrantyCode],
'' AS [WeekDisplayText],
CAST(0 AS bit) AS [EnablePCID],
'' AS [OutputBin],
'' AS [OutputWarehouse],
CAST(0 AS bit) AS [EnableLot],
'' AS [LotNum],
CAST(0 AS bit) AS [PrintPCIDContents],
CAST(0 AS bit) AS [HasAttachments],
'' AS [AttrClassID],
'' AS [DiscrepAttributeSetDescription],
'' AS [DiscrepAttributeSetShortDescription],
'' AS [ScrapAttributeSetDescription],
'' AS [ScrapAttributeSetShortDescription],
'' AS [LaborAttributeSetDescription],
'' AS [LaborAttributeSetShortDescription],
CAST(0 AS bit) AS [DisableRecallAndDelete],
'' AS [RoleCdList],
CAST(0 AS bit) AS [RowSelected],
null AS [AppointmentStart],
null AS [AppointmentEnd],
'' AS [AppointmentTitle],
'' AS [TemplateID],
CAST(0 AS bit) AS [WIPTransaction],
'' AS [DiscrepRevision],
'' AS [LaborRevision],
'' AS [ScrapRevision],
CAST(0 AS bit) AS [TrackInventoryByRevision],
CAST(0 AS bit) AS [ReportPartQtyAllowed],
ISNULL(b1.BitValues, CAST(0 AS int)) AS [BitFlag],
ISNULL([L1].[Description], '') AS [DiscrpRsnDescription],
ISNULL([L2].[LastName], '') AS [EmpBasicLastName],
ISNULL([L2].[FirstName], '') AS [EmpBasicFirstName],
ISNULL([L2].[Name], '') AS [EmpBasicName],
ISNULL([L3].[Description], '') AS [ExpenseCodeDescription],
ISNULL([L4].[HCMEnabled], CAST(0 AS bit)) AS [HCMIntregationHCMEnabled],
ISNULL([L5].[Status], '') AS [HCMStatusStatus],
ISNULL([L6].[Description], '') AS [IndirectDescription],
ISNULL([L7].[Description], '') AS [JCDeptDescription],
ISNULL([L8].[PartNum], '') AS [JobAsmblPartNum],
ISNULL([L8].[Description], '') AS [JobAsmblDescription],
ISNULL([L9].[Description], '') AS [MachineDescription],
ISNULL([L10].[OpDesc], '') AS [OpCodeOpDesc],
ISNULL([L11].[OpDesc], '') AS [OpDescOpDesc],
ISNULL([L12].[Type], CAST(0 AS int)) AS [PayMethodType],
ISNULL([L12].[SummarizePerCustomer], CAST(0 AS bit)) AS [PayMethodSummarizePerCustomer],
ISNULL([L12].[Name], '') AS [PayMethodName],
ISNULL([L13].[Description], '') AS [PhaseIDDescription],
ISNULL([L14].[Description], '') AS [ProjectDescription],
ISNULL([L15].[Description], '') AS [ResourceGrpDescription],
ISNULL([L16].[Description], '') AS [ResReasonDescription],
ISNULL([L17].[Description], '') AS [ReWorkReasonDescription],
ISNULL([L18].[RoleDescription], '') AS [RoleCdRoleDescription],
ISNULL([L19].[Description], '') AS [ScrapReasonDescription],
ISNULL([L20].[Description], '') AS [ShiftDescription],
ISNULL([L21].[Description], '') AS [TimeTypCdDescription]
FROM [Erp].[LaborDtl] AS [t0]
LEFT JOIN [Ice].[BitFlag] AS b1 ON b1.RelatedToSchemaName=N'Erp' AND b1.RelatedToTable=N'LaborDtl' AND b1.RelatedToRowId = t0.SysRowID
LEFT JOIN [Erp].[Reason] AS [L1] ON ([L1].[Company] = [t0].[Company] AND [L1].[ReasonType] = 'S'  AND [L1].[ReasonCode] = [t0].[DiscrpRsnCode])
LEFT JOIN [Erp].[EmpBasic] AS [L2] ON ([L2].[Company] = [t0].[Company] AND [L2].[EmpID] = [t0].[EmployeeNum])
LEFT JOIN [Erp].[LabExpCd] AS [L3] ON ([L3].[Company] = [t0].[Company] AND [L3].[ExpenseCode] = [t0].[ExpenseCode])
LEFT JOIN [Erp].[PRSyst] AS [L4] ON ([L4].[Company] = [t0].[Company])
LEFT JOIN [Erp].[HCMLaborDtlSync] AS [L5] ON ([L5].[Company] = [t0].[Company] AND [L5].[LaborDtlSysRowID] = [t0].[SysRowID])
LEFT JOIN [Erp].[Indirect] AS [L6] ON ([L6].[Company] = [t0].[Company] AND [L6].[IndirectCode] = [t0].[IndirectCode])
LEFT JOIN [Erp].[JCDept] AS [L7] ON ([L7].[Company] = [t0].[Company] AND [L7].[JCDept] = [t0].[JCDept])
LEFT JOIN [Erp].[JobAsmbl] AS [L8] ON ([L8].[Company] = [t0].[Company] AND [L8].[JobNum] = [t0].[JobNum] AND [L8].[AssemblySeq] = [t0].[AssemblySeq])
LEFT JOIN [Erp].[Resource] AS [L9] ON ([L9].[Company] = [t0].[Company] AND [L9].[ResourceID] = [t0].[ResourceID])
LEFT JOIN [Erp].[OpMaster] AS [L10] ON ([L10].[Company] = [t0].[Company] AND [L10].[OpCode] = [t0].[OpCode])
LEFT JOIN [Erp].[JobOper] AS [L11] ON ([L11].[Company] = [t0].[Company] AND [L11].[JobNum] = [t0].[JobNum] AND [L11].[AssemblySeq] = [t0].[AssemblySeq] AND [L11].[OprSeq] = [t0].[OprSeq])
LEFT JOIN [Erp].[PayMethod] AS [L12] ON ([L12].[Company] = [t0].[Company] AND [L12].[PMUID] = [t0].[PMUID])
LEFT JOIN [Erp].[ProjPhase] AS [L13] ON ([L13].[Company] = [t0].[Company] AND [L13].[ProjectID] = [t0].[ProjectID] AND [L13].[PhaseID] = [t0].[PhaseID])
LEFT JOIN [Erp].[Project] AS [L14] ON ([L14].[Company] = [t0].[Company] AND [L14].[ProjectID] = [t0].[ProjectID])
LEFT JOIN [Erp].[ResourceGroup] AS [L15] ON ([L15].[Company] = [t0].[Company] AND [L15].[ResourceGrpID] = [t0].[ResourceGrpID])
LEFT JOIN [Erp].[Reason] AS [L16] ON ([L16].[Company] = [t0].[Company] AND [L16].[ReasonType] = 'C'  AND [L16].[ReasonCode] = [t0].[ResReasonCode])
LEFT JOIN [Erp].[Reason] AS [L17] ON ([L17].[Company] = [t0].[Company] AND [L17].[ReasonType] = 'R'  AND [L17].[ReasonCode] = [t0].[ReworkReasonCode])
LEFT JOIN [Erp].[RoleCd] AS [L18] ON ([L18].[Company] = [t0].[Company] AND [L18].[RoleCode] = [t0].[RoleCd])
LEFT JOIN [Erp].[Reason] AS [L19] ON ([L19].[Company] = [t0].[Company] AND [L19].[ReasonType] = 'S'  AND [L19].[ReasonCode] = [t0].[ScrapReasonCode])
LEFT JOIN [Erp].[JCShift] AS [L20] ON ([L20].[Company] = [t0].[Company] AND [L20].[Shift] = [t0].[Shift])
LEFT JOIN [Erp].[TimeTypCd] AS [L21] ON ([L21].[Company] = [t0].[Company] AND [L21].[TimeTypCd] = [t0].[TimeTypCd])
	WHERE [t0].SysRowID = @SysRowID
END
