/*** Object: StoredProcedure [Erp].[_ZFW_APInvoiceAPInvDtl_GetBySysRowID] ******/

CREATE OR ALTER PROCEDURE [Erp].[_ZFW_APInvoiceAPInvDtl_GetBySysRowID]
	@SysRowID uniqueidentifier = null
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
---------------------------------------------------------------------
-- SELECT for table APInvDtl AS APInvDtl / Table Number : 1
---------------------------------------------------------------------
SELECT [t0].[Company],
[t0].[VendorNum],
[t0].[InvoiceNum],
[t0].[InvoiceLine],
[t0].[LineType],
[t0].[UnitCost],
[t0].[DocUnitCost],
[t0].[PartNum],
[t0].[PONum],
[t0].[POLine],
[t0].[PORelNum],
[t0].[Description],
[t0].[JobNum],
[t0].[AssemblySeq],
[t0].[JobSeqType],
[t0].[JobSeq],
[t0].[PurPoint],
[t0].[PackSlip],
[t0].[PackLine],
[t0].[VendorQty],
[t0].[PUM],
[t0].[OurQty],
[t0].[IUM],
[t0].[CostPerCode],
[t0].[VenPartNum],
[t0].[ExtCost],
[t0].[DocExtCost],
[t0].[TotalMiscChrg],
[t0].[DocTotalMiscChrg],
[t0].[LineComment],
[t0].[MatchDate],
[t0].[MatchFiscalYear],
[t0].[MatchFiscalPeriod],
[t0].[TaxExempt],
[t0].[TaxCatID],
[t0].[AdvancePayAmt],
[t0].[DocAdvancePayAmt],
[t0].[PurchCode],
[t0].[LineDiscAmt],
[t0].[DocLineDiscAmt],
[t0].[GlbCompany],
[t0].[GlbVendorNum],
[t0].[GlbInvoiceNum],
[t0].[GlbInvoiceLine],
[t0].[AdvGainLoss],
[t0].[MultiCompany],
[t0].[RevChargeMethod],
[t0].[OverrideReverseCharge],
[t0].[RevChargeApplied],
[t0].[Rpt1AdvancePayAmt],
[t0].[Rpt2AdvancePayAmt],
[t0].[Rpt3AdvancePayAmt],
[t0].[Rpt1ExtCost],
[t0].[Rpt2ExtCost],
[t0].[Rpt3ExtCost],
[t0].[Rpt1LineDiscAmt],
[t0].[Rpt2LineDiscAmt],
[t0].[Rpt3LineDiscAmt],
[t0].[Rpt1TotalMiscChrg],
[t0].[Rpt2TotalMiscChrg],
[t0].[Rpt3TotalMiscChrg],
[t0].[Rpt1UnitCost],
[t0].[Rpt2UnitCost],
[t0].[Rpt3UnitCost],
[t0].[DocAdvPayAppld],
[t0].[Rpt1AdvGainLoss],
[t0].[Rpt2AdvGainLoss],
[t0].[Rpt3AdvGainLoss],
[t0].[MatchFiscalYearSuffix],
[t0].[MatchFiscalCalendarID],
[t0].[TaxRegionCode],
[t0].[ContainerID],
[t0].[DropShipPackLine],
[t0].[DropShipPackSlip],
[t0].[CorrectionDtl],
[t0].[TaxConnectCalc],
[t0].[AssetNum],
[t0].[AdditionNum],
[t0].[InvoiceLineRef],
[t0].[DocAssetInvoiceBal],
[t0].[AssetBalOurQty],
[t0].[AssetQtyIUM],
[t0].[DMRNum],
[t0].[DMRActionNum],
[t0].[CreatedFromExpense],
[t0].[InUnitCost],
[t0].[DocInUnitCost],
[t0].[Rpt1InUnitCost],
[t0].[Rpt2InUnitCost],
[t0].[Rpt3InUnitCost],
[t0].[InExtCost],
[t0].[DocInExtCost],
[t0].[Rpt1InExtCost],
[t0].[Rpt2InExtCost],
[t0].[Rpt3InExtCost],
[t0].[InTotalMiscChrg],
[t0].[DocInTotalMiscChrg],
[t0].[Rpt1InTotalMiscChrg],
[t0].[Rpt2InTotalMiscChrg],
[t0].[Rpt3InTotalMiscChrg],
[t0].[InAdvancePayAmt],
[t0].[DocInAdvancePayAmt],
[t0].[Rpt1InAdvancePayAmt],
[t0].[Rpt2InAdvancePayAmt],
[t0].[Rpt3InAdvancePayAmt],
[t0].[InLineDiscAmt],
[t0].[DocInLineDiscAmt],
[t0].[Rpt1InLineDiscAmt],
[t0].[Rpt2InLineDiscAmt],
[t0].[Rpt3InLineDiscAmt],
[t0].[NoTaxRecal],
[t0].[DevInt1],
[t0].[DevInt2],
[t0].[DevDec1],
[t0].[DevDec2],
[t0].[DevDec3],
[t0].[DevDec4],
[t0].[DevLog1],
[t0].[DevLog2],
[t0].[DevChar1],
[t0].[DevChar2],
[t0].[DevDate1],
[t0].[DevDate2],
CAST([t0].[SysRevID] AS BigInt) AS SysRevID,
[t0].[SysRowID],
[t0].[ScrWithholdAmt],
[t0].[DocScrWithholdAmt],
[t0].[Rpt1ScrWithholdAmt],
[t0].[Rpt2ScrWithholdAmt],
[t0].[Rpt3ScrWithholdAmt],
[t0].[InvoiceRef],
[t0].[APTranNo],
[t0].[DocAdvPayAppliedAmt],
[t0].[Code1099ID],
[t0].[Gen1099Code],
[t0].[FormTypeID],
[t0].[DEIsServices],
[t0].[DEIsSecurityFinancialDerivative],
[t0].[DEInternationalSecuritiesID],
[t0].[DEIsInvestment],
[t0].[DEPayStatCode],
[t0].[DeferredExp],
[t0].[DEACode],
[t0].[DEAAmt],
[t0].[DEAStartDate],
[t0].[DEAEndDate],
[t0].[DEDenomination],
[t0].[ExternalPONum],
[t0].[ChangedBy],
[t0].[ChangeDate],
[t0].[MYImportNum],
[t0].[FinalInvoice],
[t0].[CommodityCode],
[t0].[TotalTax],
[t0].[DocTotalTax],
[t0].[Rpt1TotalTax],
[t0].[Rpt2TotalTax],
[t0].[Rpt3TotalTax],
[t0].[TotalSATax],
[t0].[DocTotalSATax],
[t0].[Rpt1TotalSATax],
[t0].[Rpt2TotalSATax],
[t0].[Rpt3TotalSATax],
[t0].[TotalDedTax],
[t0].[DocTotalDedTax],
[t0].[Rpt1TotalDedTax],
[t0].[Rpt2TotalDedTax],
[t0].[Rpt3TotalDedTax],
[t0].[PBInvNum],
[t0].[CancellationDtl],
[t0].[AttributeSetID],
[t0].[AttributeSetDescription],
[t0].[AttributeSetShortDescription],
[t0].[TaxExemptReasonCode],
[t0].[RevisionNum],
[t0].[ExtSysType],
[t0].[ExtSysURL],
CAST(0.0 AS decimal(20,9)) AS [AdjustmentValue],
CAST(0.0 AS decimal(20,9)) AS [AllocationAmount],
'' AS [AllocationDesc],
'' AS [AllocationID],
CAST(0 AS bit) AS [AllowGLDistAdd],
CAST(0 AS bit) AS [AllowGLDistAllocation],
CAST(0 AS bit) AS [AllowGLDistDelete],
CAST(0 AS bit) AS [AllowJobMiscAdd],
CAST(0 AS bit) AS [AllowJobMiscDelete],
CAST(0 AS bit) AS [AllowJobMiscUpdate],
'' AS [BaseCurrencyID],
'' AS [BaseCurrSymbol],
'' AS [CurrencyCode],
'' AS [CurrencyID],
CAST(0 AS bit) AS [CurrencySwitch],
'' AS [CurrSymbol],
'' AS [DEACodeDesc],
CAST(0 AS bit) AS [DEAScheduled],
CAST(0 AS bit) AS [DebitMemo],
CAST(0.0 AS decimal(20,9)) AS [Distributed],
CAST(0.0 AS decimal(20,9)) AS [DocAdjustmentValue],
CAST(0.0 AS decimal(20,9)) AS [DocAllocationAmount],
CAST(0.0 AS decimal(20,9)) AS [DocDistributed],
CAST(0.0 AS decimal(20,9)) AS [DocDspLineTotal],
CAST(0.0 AS decimal(20,9)) AS [DocExpense],
CAST(0.0 AS decimal(20,9)) AS [DocGLLineTotal],
CAST(0.0 AS decimal(20,9)) AS [DocInTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [DocLineExpenses],
CAST(0.0 AS decimal(20,9)) AS [DocLineSubtotal],
CAST(0.0 AS decimal(20,9)) AS [DocLineTotal],
CAST(0.0 AS decimal(20,9)) AS [DocNonDeducTaxExpense],
CAST(0.0 AS decimal(20,9)) AS [DocOrgExtCost],
CAST(0.0 AS decimal(20,9)) AS [DocPEDetAmt],
CAST(0.0 AS decimal(20,9)) AS [DocRecognized],
CAST(0.0 AS decimal(20,9)) AS [DocRemaining],
CAST(0.0 AS decimal(20,9)) AS [DocScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [DocScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [DocScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [DocScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [DocScrUnitCost],
CAST(0.0 AS decimal(20,9)) AS [DocTotDistribAmt],
CAST(0.0 AS decimal(20,9)) AS [DocUnrecognized],
CAST(0.0 AS decimal(20,9)) AS [DocVariance],
CAST(0 AS bit) AS [DropShipment],
CAST(0.0 AS decimal(20,9)) AS [DspAllocationAmount],
CAST(0.0 AS decimal(20,9)) AS [DspLineTotal],
CAST(0 AS bit) AS [EnableDiscountAmt],
CAST(0 AS bit) AS [EnableIntrastat],
CAST(0 AS bit) AS [EnableIntrastatDsp],
CAST(0 AS bit) AS [EnablePurchaseCode],
CAST(0 AS bit) AS [EnableRevCharge],
CAST(0 AS bit) AS [EnableScrWithholdAmt],
CAST(1 AS bit) AS [EnableShipmentID],
CAST(0 AS bit) AS [EnableSubCData],
CAST(0 AS bit) AS [EnableSupplierXRef],
CAST(0.0 AS decimal(20,9)) AS [Expense],
'' AS [GLAccount],
CAST(0.0 AS decimal(20,9)) AS [GLLineTotal],
'' AS [GridVenPartNum],
'' AS [GroupID],
CAST(0 AS bit) AS [InPrice],
CAST(0.0 AS decimal(20,9)) AS [InTaxAmt],
CAST(0 AS bit) AS [IsAdvance],
CAST(0 AS bit) AS [JPTaxAdjustment],
CAST(0.0 AS decimal(20,9)) AS [LineExpenses],
CAST(0.0 AS decimal(20,9)) AS [LineSubtotal],
CAST(0.0 AS decimal(20,9)) AS [LineTotal],
'' AS [LineTypeDescription],
CAST(0.0 AS decimal(20,9)) AS [NonDeducTaxExpense],
CAST(0.0 AS decimal(20,9)) AS [OrgExtCost],
CAST(0.0 AS decimal(20,9)) AS [PEDetAmt],
N'E' AS [POCostPerCode],
CAST(0.0 AS decimal(20,9)) AS [PODocUnitCost],
'' AS [POLineDesc],
'' AS [POPartNum],
'' AS [POPUM],
CAST(0.0 AS decimal(20,9)) AS [POReceivedQty],
'' AS [PORelIUM],
CAST(0.0 AS decimal(20,9)) AS [PORelOurQty],
CAST(0.0 AS decimal(20,9)) AS [PORelQty],
CAST(0 AS bit) AS [Posted],
CAST(0.0 AS decimal(20,9)) AS [POUnitCost],
'' AS [POVenPartNum],
'' AS [POWarn],
CAST(0 AS bit) AS [Print1099],
'' AS [RcptDestination],
'' AS [RcptIUM],
CAST(0.0 AS decimal(20,9)) AS [RcptOurQty],
'' AS [RcptPartDescription],
'' AS [RcptPartNum],
'' AS [RcptPUM],
null AS [RcptReceiptDate],
CAST(0.0 AS decimal(20,9)) AS [RcptVendorQty],
'' AS [RcptVenPartNum],
CAST(0 AS bit) AS [RecalcGLAcct],
CAST(0.0 AS decimal(20,9)) AS [Recognized],
CAST(0.0 AS decimal(20,9)) AS [Remaining],
'' AS [RevChargeMethodDesc],
CAST(0.0 AS decimal(20,9)) AS [Rpt1AdjustmentValue],
CAST(0.0 AS decimal(20,9)) AS [Rpt1AllocationAmount],
CAST(0.0 AS decimal(20,9)) AS [Rpt1Distributed],
CAST(0.0 AS decimal(20,9)) AS [Rpt1DspLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1Expense],
CAST(0.0 AS decimal(20,9)) AS [Rpt1GLLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1InTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1LineExpenses],
CAST(0.0 AS decimal(20,9)) AS [Rpt1LineSubTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1LineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1NonDeducTaxExpense],
CAST(0.0 AS decimal(20,9)) AS [Rpt1OrgExtCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt1PEDetAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1POUnitCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt1Recognized],
CAST(0.0 AS decimal(20,9)) AS [Rpt1Remaining],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrExtCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrLineDiscAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalMiscChrg],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrUnitCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt1TotDistribAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1Unrecognized],
CAST(0.0 AS decimal(20,9)) AS [Rpt1Variance],
CAST(0.0 AS decimal(20,9)) AS [Rpt2AdjustmentValue],
CAST(0.0 AS decimal(20,9)) AS [Rpt2AllocationAmount],
CAST(0.0 AS decimal(20,9)) AS [Rpt2Distributed],
CAST(0.0 AS decimal(20,9)) AS [Rpt2DspLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2Expense],
CAST(0.0 AS decimal(20,9)) AS [Rpt2GLLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2InTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2LineExpenses],
CAST(0.0 AS decimal(20,9)) AS [Rpt2LineSubtotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2LineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2NonDeducTaxExpense],
CAST(0.0 AS decimal(20,9)) AS [Rpt2OrgExtCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt2PEDetAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2POUnitCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt2Recognized],
CAST(0.0 AS decimal(20,9)) AS [Rpt2Remaining],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrExtCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrLineDiscAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalMiscChrg],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrUnitCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt2TotDistribAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2Unrecognized],
CAST(0.0 AS decimal(20,9)) AS [Rpt2Variance],
CAST(0.0 AS decimal(20,9)) AS [Rpt3AdjustmentValue],
CAST(0.0 AS decimal(20,9)) AS [Rpt3AllocationAmount],
CAST(0.0 AS decimal(20,9)) AS [Rpt3Distributed],
CAST(0.0 AS decimal(20,9)) AS [Rpt3DspLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3Expense],
CAST(0.0 AS decimal(20,9)) AS [Rpt3GLLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3InTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3LineExpenses],
CAST(0.0 AS decimal(20,9)) AS [Rpt3LineSubtotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3LineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3NonDeducTaxExpense],
CAST(0.0 AS decimal(20,9)) AS [Rpt3OrgExtCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt3PEDetAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3POUnitCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt3Recognized],
CAST(0.0 AS decimal(20,9)) AS [Rpt3Remaining],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrExtCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrLineDiscAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalMiscChrg],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrUnitCost],
CAST(0.0 AS decimal(20,9)) AS [Rpt3TotDistribAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3Unrecognized],
CAST(0.0 AS decimal(20,9)) AS [Rpt3Variance],
CAST(0.0 AS decimal(20,9)) AS [ScrDocExtCost],
CAST(0.0 AS decimal(20,9)) AS [ScrDocLineDiscAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotalMiscChrg],
CAST(0.0 AS decimal(20,9)) AS [ScrExtCost],
CAST(0.0 AS decimal(20,9)) AS [ScrInvoiceBal],
'' AS [ScrInvoiceRef],
CAST(0.0 AS decimal(20,9)) AS [ScrLineDiscAmt],
'' AS [ScrLineType],
CAST(0.0 AS decimal(20,9)) AS [ScrOurQty],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalMiscChrg],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [ScrUnitCost],
CAST(0.0 AS decimal(20,9)) AS [ScrVendorQty],
CAST(0.0 AS decimal(20,9)) AS [TotDistribAmt],
CAST(0.0 AS decimal(20,9)) AS [Unrecognized],
CAST(0 AS bit) AS [UpdateExtCreateLineGL],
CAST(0 AS bit) AS [UsePurchaseCode],
CAST(0.0 AS decimal(20,9)) AS [Variance],
CAST(0 AS bit) AS [UpdateExtOverrideRcpts],
CAST(null AS uniqueidentifier) AS [RelatedToRcvDtlSysRowID],
CAST(0 AS bit) AS [EnableAttributeSetBtn],
'' AS [DEPayStatCodeDescr],
'' AS [DEDenominationDescr],
'' AS [PORevisionNum],
'' AS [RcptRevisionNum],
ISNULL(b1.BitValues, CAST(0 AS int)) AS [BitFlag],
ISNULL([L1].[Description], '') AS [AssemblySeqDescription],
ISNULL([L2].[AssetDescription], '') AS [AssetNumAssetDescription],
ISNULL([L3].[Description], '') AS [Code1099Description],
ISNULL([L4].[Description], '') AS [CommodityCodeDescription],
ISNULL([L5].[ContainerDescription], '') AS [ContainerIDContainerDescription],
ISNULL([L6].[Description], '') AS [FormTypeDescription],
ISNULL([L7].[PurchDesc], '') AS [GLPurchPurchDesc],
ISNULL([L8].[DebitMemo], CAST(0 AS bit)) AS [InvoiceNumDebitMemo],
ISNULL([L8].[Posted], CAST(0 AS bit)) AS [InvoiceNumPosted],
ISNULL([L8].[Description], '') AS [InvoiceNumDescription],
ISNULL([L8].[CurrencyCode], '') AS [InvoiceNumCurrencyCode],
ISNULL([L9].[PartDescription], '') AS [JobNumPartDescription],
ISNULL([L10].[TrackInventoryAttributes], CAST(0 AS bit)) AS [PartNumTrackInventoryAttributes],
ISNULL([L10].[TrackSerialNum], CAST(0 AS bit)) AS [PartNumTrackSerialNum],
ISNULL([L10].[TrackLots], CAST(0 AS bit)) AS [PartNumTrackLots],
ISNULL([L10].[PricePerCode], '') AS [PartNumPricePerCode],
ISNULL([L10].[IUM], '') AS [PartNumIUM],
ISNULL([L10].[SellingFactor], CAST(0.0 AS decimal(20,9))) AS [PartNumSellingFactor],
ISNULL([L10].[TrackDimension], CAST(0 AS bit)) AS [PartNumTrackDimension],
ISNULL([L10].[PartDescription], '') AS [PartNumPartDescription],
ISNULL([L10].[SalesUM], '') AS [PartNumSalesUM],
ISNULL([L10].[AttrClassID], '') AS [PartNumAttrClassID],
ISNULL([L11].[LineDesc], '') AS [POLineLineDesc],
ISNULL([L11].[VenPartNum], '') AS [POLineVenPartNum],
ISNULL([L11].[PartNum], '') AS [POLinePartNum],
ISNULL([L12].[Description], '') AS [TaxCatIDDescription],
ISNULL([L13].[Name], '') AS [VendorNumName],
ISNULL([L13].[Address2], '') AS [VendorNumAddress2],
ISNULL([L13].[Country], '') AS [VendorNumCountry],
ISNULL([L13].[City], '') AS [VendorNumCity],
ISNULL([L13].[DefaultFOB], '') AS [VendorNumDefaultFOB],
ISNULL([L13].[CurrencyCode], '') AS [VendorNumCurrencyCode],
ISNULL([L13].[State], '') AS [VendorNumState],
ISNULL([L13].[TermsCode], '') AS [VendorNumTermsCode],
ISNULL([L13].[VendorID], '') AS [VendorNumVendorID],
ISNULL([L13].[Address3], '') AS [VendorNumAddress3],
ISNULL([L13].[ZIP], '') AS [VendorNumZIP],
ISNULL([L13].[Address1], '') AS [VendorNumAddress1],
ISNULL([L14].[Name], '') AS [VendorPPName],
ISNULL([L15].[ShipToConName], '') AS [vrPONumShipToConName],
ISNULL([L15].[ShipName], '') AS [vrPONumShipName]
FROM [Erp].[APInvDtl] AS [t0]
LEFT JOIN [Ice].[BitFlag] AS b1 ON b1.RelatedToSchemaName=N'Erp' AND b1.RelatedToTable=N'APInvDtl' AND b1.RelatedToRowId = t0.SysRowID
LEFT JOIN [Erp].[JobAsmbl] AS [L1] ON ([L1].[Company] = [t0].[Company] AND [L1].[JobNum] = [t0].[JobNum] AND [L1].[AssemblySeq] = [t0].[AssemblySeq])
LEFT JOIN [Erp].[FAsset] AS [L2] ON ([L2].[Company] = [t0].[Company] AND [L2].[AssetNum] = [t0].[AssetNum])
LEFT JOIN [Erp].[Code1099] AS [L3] ON ([L3].[Company] = [t0].[Company] AND [L3].[FormTypeID] = [t0].[FormTypeID] AND [L3].[Code1099ID] = [t0].[Code1099ID])
LEFT JOIN [Erp].[ICommCode] AS [L4] ON ([L4].[Company] = [t0].[Company] AND [L4].[CommodityCode] = [t0].[CommodityCode])
LEFT JOIN [Erp].[ContainerHeader] AS [L5] ON ([L5].[Company] = [t0].[Company] AND [L5].[ContainerID] = [t0].[ContainerID])
LEFT JOIN [Erp].[FormType] AS [L6] ON ([L6].[Company] = [t0].[Company] AND [L6].[FormTypeID] = [t0].[FormTypeID])
LEFT JOIN [Erp].[GLPurch] AS [L7] ON ([L7].[Company] = [t0].[Company] AND [L7].[PurchCode] = [t0].[PurchCode])
LEFT JOIN [Erp].[APInvHed] AS [L8] ON ([L8].[Company] = [t0].[Company] AND [L8].[VendorNum] = [t0].[VendorNum] AND [L8].[InvoiceNum] = [t0].[InvoiceNum])
LEFT JOIN [Erp].[JobHead] AS [L9] ON ([L9].[Company] = [t0].[Company] AND [L9].[JobNum] = [t0].[JobNum])
LEFT JOIN [Erp].[Part] AS [L10] ON ([L10].[Company] = [t0].[Company] AND [L10].[PartNum] = [t0].[PartNum])
LEFT JOIN [Erp].[PODetail] AS [L11] ON ([L11].[Company] = [t0].[Company] AND [L11].[PONUM] = [t0].[PONum] AND [L11].[POLine] = [t0].[POLine])
LEFT JOIN [Erp].[TaxCat] AS [L12] ON ([L12].[Company] = [t0].[Company] AND [L12].[TaxCatID] = [t0].[TaxCatID])
LEFT JOIN [Erp].[Vendor] AS [L13] ON ([L13].[Company] = [t0].[Company] AND [L13].[VendorNum] = [t0].[VendorNum])
LEFT JOIN [Erp].[VendorPP] AS [L14] ON ([L14].[Company] = [t0].[Company] AND [L14].[VendorNum] = [t0].[VendorNum] AND [L14].[PurPoint] = [t0].[PurPoint])
LEFT JOIN [Erp].[POHeader] AS [L15] ON ([L15].[Company] = [t0].[Company] AND [L15].[PONum] = [t0].[PONum])
	WHERE [t0].SysRowID = @SysRowID
END
