/*** Object: StoredProcedure [Erp].[_ZFW_APInvoiceAPIHAPInvMsc_GetBySysRowID] ******/

CREATE OR ALTER PROCEDURE [Erp].[_ZFW_APInvoiceAPIHAPInvMsc_GetBySysRowID]
	@SysRowID uniqueidentifier = null
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
---------------------------------------------------------------------
-- SELECT for table APInvMsc AS APIHAPInvMsc / Table Number : 1
---------------------------------------------------------------------
SELECT [t0].[Company],
[t0].[VendorNum],
[t0].[InvoiceNum],
[t0].[InvoiceLine],
[t0].[MscNum],
[t0].[MiscCode],
[t0].[Description],
[t0].[MiscAmt],
[t0].[DocMiscAmt],
[t0].[PONum],
[t0].[POLine],
[t0].[SeqNum],
[t0].[TaxCatID],
[t0].[GlbCompany],
[t0].[GlbVendorNum],
[t0].[GlbInvoiceNum],
[t0].[GlbInvoiceLine],
[t0].[GlbMscNum],
[t0].[Rpt1MiscAmt],
[t0].[Rpt2MiscAmt],
[t0].[Rpt3MiscAmt],
[t0].[InvExpSeq],
[t0].[LCFlag],
[t0].[ContainerID],
[t0].[PurPoint],
[t0].[PackSlip],
[t0].[Percentage],
[t0].[Type],
[t0].[LCVendorNum],
[t0].[LCDisburseMethod],
[t0].[InMiscAmt],
[t0].[DocInMiscAmt],
[t0].[Rpt1InMiscAmt],
[t0].[Rpt2InMiscAmt],
[t0].[Rpt3InMiscAmt],
[t0].[DevInt1],
[t0].[DevInt2],
[t0].[DevDec1],
[t0].[DevDec2],
[t0].[DevDec3],
[t0].[DevDec4],
[t0].[DevLog1],
[t0].[DevLog2],
[t0].[DevChar1],
[t0].[DevChar2],
[t0].[DevDate1],
[t0].[DevDate2],
CAST([t0].[SysRevID] AS BigInt) AS SysRevID,
[t0].[SysRowID],
[t0].[CorrectionDtl],
[t0].[NoTaxRecalc],
[t0].[Code1099ID],
[t0].[FormTypeID],
[t0].[Gen1099Code],
[t0].[TaxExemptReasonCode],
[t0].[PlasticPackTaxReportID],
CAST(0.0 AS decimal(20,9)) AS [AllocBasis],
'' AS [BaseCurrSymbol],
'' AS [CurrencyCode],
CAST(0 AS bit) AS [CurrencySwitch],
'' AS [CurrSymbol],
CAST(0 AS bit) AS [DebitMemo],
CAST(0.0 AS decimal(20,9)) AS [DocAllocAmt],
CAST(0.0 AS decimal(20,9)) AS [DocScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [DocScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [DocScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [DocUnallocAmt],
'' AS [GroupID],
CAST(0 AS bit) AS [InPrice],
CAST(1 AS bit) AS [LCEnabled],
CAST(0 AS bit) AS [Posted],
'' AS [RecordSource],
CAST(0.0 AS decimal(20,9)) AS [Rpt1AllocAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrMiscAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1UnallocAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2AllocAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrMiscAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2UnallocAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3AllocAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrMiscAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3UnallocAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocMiscAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrMiscAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalDedTax],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalSATax],
CAST(0.0 AS decimal(20,9)) AS [ScrTotalTax],
CAST(0.0 AS decimal(20,9)) AS [UnallocAmt],
CAST(0.0 AS decimal(20,9)) AS [AllocAmt],
ISNULL(b1.BitValues, CAST(0 AS int)) AS [BitFlag],
ISNULL([L1].[Description], '') AS [Code1099Description],
ISNULL([L2].[Description], '') AS [FormTypeDescription],
ISNULL([L3].[Description], '') AS [MiscCodeDescription],
ISNULL([L3].[LCDisburseMethod], '') AS [MiscCodeLCDisburseMethod],
ISNULL([L3].[LCAmount], CAST(0.0 AS decimal(20,9))) AS [MiscCodeLCAmount],
ISNULL([L3].[LCCurrencyCode], '') AS [MiscCodeLCCurrencyCode]
FROM [Erp].[APInvMsc] AS [t0]
LEFT JOIN [Ice].[BitFlag] AS b1 ON b1.RelatedToSchemaName=N'Erp' AND b1.RelatedToTable=N'APInvMsc' AND b1.RelatedToRowId = t0.SysRowID
LEFT JOIN [Erp].[Code1099] AS [L1] ON ([L1].[Company] = [t0].[Company] AND [L1].[FormTypeID] = [t0].[FormTypeID] AND [L1].[Code1099ID] = [t0].[Code1099ID])
LEFT JOIN [Erp].[FormType] AS [L2] ON ([L2].[Company] = [t0].[Company] AND [L2].[FormTypeID] = [t0].[FormTypeID])
LEFT JOIN [Erp].[PurMisc] AS [L3] ON ([L3].[Company] = [t0].[Company] AND [L3].[MiscCode] = [t0].[MiscCode])
	WHERE [t0].SysRowID = @SysRowID
END
