/*** Object: StoredProcedure [Erp].[_ZFW_APInvoiceAPIHAPLnTax_GetBySysRowID] ******/

CREATE OR ALTER PROCEDURE [Erp].[_ZFW_APInvoiceAPIHAPLnTax_GetBySysRowID]
	@SysRowID uniqueidentifier = null
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
---------------------------------------------------------------------
-- SELECT for table APLnTax AS APIHAPLnTax / Table Number : 1
---------------------------------------------------------------------
SELECT [t0].[Company],
[t0].[VendorNum],
[t0].[InvoiceNum],
[t0].[TaxCode],
[t0].[TaxableAmt],
[t0].[DocTaxableAmt],
[t0].[Percent],
[t0].[TaxAmt],
[t0].[DocTaxAmt],
[t0].[ReportableAmt],
[t0].[DocReportableAmt],
[t0].[Manual],
[t0].[SysCalcTaxableAmt],
[t0].[SysCalcDocTaxableAmt],
[t0].[SysCalcReportableAmt],
[t0].[SysCalcDocReportableAmt],
[t0].[ECAcquisitionSeq],
[t0].[GlbCompany],
[t0].[GlbVendorNum],
[t0].[GlbInvoiceNum],
[t0].[GlbTaxCode],
[t0].[GlbECAcquisitionSeq],
[t0].[ReverseCharge],
[t0].[Rpt1ReportableAmt],
[t0].[Rpt2ReportableAmt],
[t0].[Rpt3ReportableAmt],
[t0].[Rpt1TaxableAmt],
[t0].[Rpt2TaxableAmt],
[t0].[Rpt3TaxableAmt],
[t0].[Rpt1TaxAmt],
[t0].[Rpt2TaxAmt],
[t0].[Rpt3TaxAmt],
[t0].[Rpt1SysCalcTaxableAmt],
[t0].[Rpt1SysCalcReportableAmt],
[t0].[Rpt2SysCalcTaxableAmt],
[t0].[Rpt2SysCalcReportableAmt],
[t0].[Rpt3SysCalcTaxableAmt],
[t0].[Rpt3SysCalcReportableAmt],
[t0].[RateCode],
[t0].[CollectionType],
[t0].[Timing],
[t0].[ExemptType],
[t0].[ExemptPercent],
[t0].[ResolutionNum],
[t0].[ResolutionDate],
[t0].[TaxRateDate],
[t0].[DefTaxableAmt],
[t0].[DocDefTaxableAmt],
[t0].[Rpt1DefTaxableAmt],
[t0].[Rpt2DefTaxableAmt],
[t0].[Rpt3DefTaxableAmt],
[t0].[DefTaxAmt],
[t0].[DocDefTaxAmt],
[t0].[Rpt1DefTaxAmt],
[t0].[Rpt2DefTaxAmt],
[t0].[Rpt3DefTaxAmt],
[t0].[ManAdd],
[t0].[DedTaxAmt],
[t0].[DocDedTaxAmt],
[t0].[Rpt1DedTaxAmt],
[t0].[Rpt2DedTaxAmt],
[t0].[Rpt3DedTaxAmt],
[t0].[FixedAmount],
[t0].[DocFixedAmount],
[t0].[Rpt1FixedAmount],
[t0].[Rpt2FixedAmount],
[t0].[Rpt3FixedAmount],
[t0].[GlbRateCode],
[t0].[TextCode],
[t0].[TaxAmtVar],
[t0].[DocTaxAmtVar],
[t0].[Rpt1TaxAmtVar],
[t0].[Rpt2TaxAmtVar],
[t0].[Rpt3TaxAmtVar],
[t0].[DefTaxDate],
[t0].[TaxFuture],
[t0].[STPProcessed],
[t0].[InvoiceLine],
[t0].[DevInt1],
[t0].[DevInt2],
[t0].[DevDec1],
[t0].[DevDec2],
[t0].[DevDec3],
[t0].[DevDec4],
[t0].[DevLog1],
[t0].[DevLog2],
[t0].[DevChar1],
[t0].[DevChar2],
[t0].[DevDate1],
[t0].[DevDate2],
CAST([t0].[SysRevID] AS BigInt) AS SysRevID,
[t0].[SysRowID],
[t0].[MovementNum],
[t0].[ChangedBy],
[t0].[ChangedOn],
[t0].[ExemptReasonCode],
'' AS [CurrencyCode],
CAST(0 AS bit) AS [CurrencySwitch],
CAST(0 AS bit) AS [DisableManual],
CAST(0.0 AS decimal(20,9)) AS [DocScrDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [DocScrReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [DocScrTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [DocScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [DocScrTaxAmtVar],
'' AS [GroupID],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTaxAmtVar],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTaxAmtVar],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTaxAmtVar],
CAST(0.0 AS decimal(20,9)) AS [ScrDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTaxAmtVar],
ISNULL(b1.BitValues, CAST(0 AS int)) AS [BitFlag],
ISNULL([L1].[Description], '') AS [InvoiceNumDescription],
ISNULL([L2].[Description], '') AS [RateCodeDescription],
ISNULL([L3].[Description], '') AS [TaxCodeDescription],
ISNULL([L4].[Address1], '') AS [VendorNumAddress1],
ISNULL([L4].[TermsCode], '') AS [VendorNumTermsCode],
ISNULL([L4].[Address2], '') AS [VendorNumAddress2],
ISNULL([L4].[VendorID], '') AS [VendorNumVendorID],
ISNULL([L4].[ZIP], '') AS [VendorNumZIP],
ISNULL([L4].[Address3], '') AS [VendorNumAddress3],
ISNULL([L4].[City], '') AS [VendorNumCity],
ISNULL([L4].[Country], '') AS [VendorNumCountry],
ISNULL([L4].[CurrencyCode], '') AS [VendorNumCurrencyCode],
ISNULL([L4].[DefaultFOB], '') AS [VendorNumDefaultFOB],
ISNULL([L4].[Name], '') AS [VendorNumName],
ISNULL([L4].[State], '') AS [VendorNumState]
FROM [Erp].[APLnTax] AS [t0]
LEFT JOIN [Ice].[BitFlag] AS b1 ON b1.RelatedToSchemaName=N'Erp' AND b1.RelatedToTable=N'APLnTax' AND b1.RelatedToRowId = t0.SysRowID
LEFT JOIN [Erp].[APInvHed] AS [L1] ON ([L1].[Company] = [t0].[Company] AND [L1].[VendorNum] = [t0].[VendorNum] AND [L1].[InvoiceNum] = [t0].[InvoiceNum])
LEFT JOIN [Erp].[SalesTRC] AS [L2] ON ([L2].[Company] = [t0].[Company] AND [L2].[TaxCode] = [t0].[TaxCode] AND [L2].[RateCode] = [t0].[RateCode])
LEFT JOIN [Erp].[SalesTax] AS [L3] ON ([L3].[Company] = [t0].[Company] AND [L3].[TaxCode] = [t0].[TaxCode])
LEFT JOIN [Erp].[Vendor] AS [L4] ON ([L4].[Company] = [t0].[Company] AND [L4].[VendorNum] = [t0].[VendorNum])
	WHERE [t0].SysRowID = @SysRowID
END
