/*** Object: StoredProcedure [Erp].[_ZFW_APInvoiceAPInvHed_GetBySysRowID] ******/

CREATE OR ALTER PROCEDURE [Erp].[_ZFW_APInvoiceAPInvHed_GetBySysRowID]
	@SysRowID uniqueidentifier = null
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
---------------------------------------------------------------------
-- SELECT for table APInvHed AS APInvHed / Table Number : 1
---------------------------------------------------------------------
SELECT [t0].[Company],
[t0].[OpenPayable],
[t0].[VendorNum],
[t0].[InvoiceNum],
[t0].[DebitMemo],
[t0].[InvoiceDate],
[t0].[TermsCode],
[t0].[TaxAmt],
[t0].[DocTaxAmt],
[t0].[DiscountDate],
[t0].[DiscountAmt],
[t0].[DocDiscountAmt],
[t0].[DueDate],
[t0].[PayDates],
[t0].[PayAmounts],
[t0].[DocPayAmounts],
[t0].[GLPosted],
[t0].[GroupID],
[t0].[Posted],
[t0].[FiscalYear],
[t0].[FiscalPeriod],
[t0].[StartUp],
[t0].[InvoiceRef],
[t0].[EntryPerson],
[t0].[InvoiceComment],
[t0].[InvoiceAmt],
[t0].[DocInvoiceAmt],
[t0].[DocInvoiceVendorAmt],
[t0].[InvoiceBal],
[t0].[DocInvoiceBal],
[t0].[UnpostedBal],
[t0].[DocUnpostedBal],
[t0].[InvoiceHeld],
[t0].[PayHold],
[t0].[Description],
[t0].[CurrencyCode],
[t0].[ExchangeRate],
[t0].[LockRate],
[t0].[REFPONum],
[t0].[TaxRegionCode],
[t0].[JournalNum],
[t0].[JournalCode],
[t0].[UpdateTax],
[t0].[InvoiceVendorAmt],
[t0].[LegalNumber],
[t0].[ExternalID],
[t0].[FixedAmt],
[t0].[XRefInvoiceNum],
[t0].[GlbCompany],
[t0].[GlbVendorNum],
[t0].[GlbInvoiceNum],
[t0].[DepGainLoss],
[t0].[CPay],
[t0].[CPayLinked],
[t0].[CPayLegalNumber],
[t0].[CPayCheckNum],
[t0].[CPayCheckDate],
[t0].[CPayInvoiceBal],
[t0].[CPayDocInvoiceBal],
[t0].[Rounding],
[t0].[GLControlType],
[t0].[DocRounding],
[t0].[GLControlCode],
[t0].[Rpt1DiscountAmt],
[t0].[Rpt2DiscountAmt],
[t0].[Rpt3DiscountAmt],
[t0].[Rpt1InvoiceAmt],
[t0].[Rpt2InvoiceAmt],
[t0].[Rpt3InvoiceAmt],
[t0].[Rpt1InvoiceBal],
[t0].[Rpt2InvoiceBal],
[t0].[Rpt3InvoiceBal],
[t0].[Rpt1InvoiceVendorAmt],
[t0].[Rpt2InvoiceVendorAmt],
[t0].[Rpt3InvoiceVendorAmt],
[t0].[Rpt1PayAmounts],
[t0].[Rpt2PayAmounts],
[t0].[Rpt3PayAmounts],
[t0].[Rpt1Rounding],
[t0].[Rpt2Rounding],
[t0].[Rpt3Rounding],
[t0].[Rpt1TaxAmt],
[t0].[Rpt2TaxAmt],
[t0].[Rpt3TaxAmt],
[t0].[Rpt1UnpostedBal],
[t0].[Rpt2UnpostedBal],
[t0].[Rpt3UnpostedBal],
[t0].[RateGrpCode],
[t0].[Rpt1CPayInvoiceBal],
[t0].[Rpt2CPayInvoiceBal],
[t0].[Rpt3CPayInvoiceBal],
[t0].[AllowOverrideLI],
[t0].[MatchedFromLI],
[t0].[ApplyDate],
[t0].[FiscalYearSuffix],
[t0].[FiscalCalendarID],
[t0].[TaxPoint],
[t0].[TaxRateDate],
[t0].[ReadyToCalc],
[t0].[RecalcBeforePost],
[t0].[GetDfltTaxIds],
[t0].[PMUID],
[t0].[PayDiscDays],
[t0].[PayDiscPer],
[t0].[WithholdAmt],
[t0].[DocWithholdAmt],
[t0].[Rpt1WithholdAmt],
[t0].[Rpt2WithholdAmt],
[t0].[Rpt3WithholdAmt],
[t0].[PayDiscPartPay],
[t0].[PIPayment],
[t0].[CorrectionInv],
[t0].[TaxRateGrpCode],
[t0].[LockTaxRate],
[t0].[SEBankRef],
[t0].[SEPayCode],
[t0].[GUIFormatCode],
[t0].[GUITaxTypeCode],
[t0].[GUIDeductCode],
[t0].[PrePayment],
[t0].[APLOCID],
[t0].[Plant],
[t0].[GUIImportTaxBasis],
[t0].[DocGUIImportTaxBasis],
[t0].[Rpt1GUIImportTaxBasis],
[t0].[Rpt2GUIImportTaxBasis],
[t0].[Rpt3GUIImportTaxBasis],
[t0].[OvrDefTaxDate],
[t0].[Linked],
[t0].[ClaimRef],
[t0].[EmpID],
[t0].[InBankFile],
[t0].[CNConfirmDate],
[t0].[BankID],
[t0].[SelfLegalNumber],
[t0].[SelfTranDocTypeID],
[t0].[MainSite],
[t0].[CardCode],
[t0].[SiteCode],
[t0].[BankGiroAcctNbr],
[t0].[BranchID],
[t0].[SupAgentName],
[t0].[SupAgentTaxRegNo],
[t0].[NonDeductCode],
[t0].[AssetTypeCode],
[t0].[Cash],
[t0].[CreditCard],
[t0].[Normal],
[t0].[CardID],
[t0].[CardHolderTaxID],
[t0].[CardMemberName],
[t0].[Excluded],
[t0].[Deferred],
[t0].[NonDeductAmt],
[t0].[NonDeductDocAmt],
[t0].[NonDeductRpt1Amt],
[t0].[NonDeductRpt2Amt],
[t0].[NonDeductRpt3Amt],
[t0].[NonDeductVATAmt],
[t0].[NonDeductVATDocAmt],
[t0].[NonDeductVATRpt1Amt],
[t0].[NonDeductVATRpt2Amt],
[t0].[NonDeductVATRpt3Amt],
[t0].[ImportNum],
[t0].[ImportedFrom],
[t0].[ImportedDate],
[t0].[AdvTaxInv],
[t0].[InPrice],
[t0].[TranDocTypeID],
[t0].[DevInt1],
[t0].[DevInt2],
[t0].[DevDec1],
[t0].[DevDec2],
[t0].[DevDec3],
[t0].[DevDec4],
[t0].[DevLog1],
[t0].[DevLog2],
[t0].[DevChar1],
[t0].[DevChar2],
[t0].[DevDate1],
[t0].[DevDate2],
[t0].[PaymentNumber],
[t0].[CycleCode],
[t0].[Duration],
[t0].[EndDate],
[t0].[MaxValueAmt],
[t0].[DocMaxValueAmt],
[t0].[Rpt1MaxValueAmt],
[t0].[Rpt2MaxValueAmt],
[t0].[Rpt3MaxValueAmt],
[t0].[HoldInvoice],
[t0].[CopyLatestInvoice],
[t0].[OverrideEndDate],
[t0].[CycleInactive],
[t0].[RecurSource],
[t0].[InstanceNum],
[t0].[RecurBalance],
[t0].[DocRecurBalance],
[t0].[Rpt1RecurBalance],
[t0].[Rpt2RecurBalance],
[t0].[Rpt3RecurBalance],
[t0].[LastDate],
[t0].[IsRecurring],
[t0].[InvoiceNumList],
[t0].[IsMaxValue],
CAST([t0].[SysRevID] AS BigInt) AS SysRevID,
[t0].[SysRowID],
[t0].[CHISRCodeLine],
[t0].[DMReason],
[t0].[UrgentPayment],
[t0].[AGDocPageNum],
[t0].[AGCAICAEMark],
[t0].[AGCAICAENum],
[t0].[AGCAICAEExpirationDate],
[t0].[AGAvTaxCreditFlag],
[t0].[AGUseGoodDefaultMark],
[t0].[AGCustomsClearanceNum],
[t0].[AGCustomsCode],
[t0].[AGDestinationCode],
[t0].[HeadNum],
[t0].[TranType],
[t0].[TaxSvcID],
[t0].[TWDeclareYear],
[t0].[TWDeclarePeriod],
[t0].[APChkGrpID],
[t0].[InvoiceType],
[t0].[PEComputationalCost],
[t0].[ReferencedByBOE],
[t0].[PEDUARefNum],
[t0].[CustomsNumber],
[t0].[ReceivedDate],
[t0].[CustOverride],
[t0].[PrePaymentNum],
[t0].[PrePaymentAmt],
[t0].[DocPrePaymentAmt],
[t0].[Rpt1PrePaymentAmt],
[t0].[Rpt2PrePaymentAmt],
[t0].[Rpt3PrePaymentAmt],
[t0].[PEAPPayNum],
[t0].[PEDetTaxAmt],
[t0].[PEDetTaxCurrencyCode],
[t0].[PESUNATDepAmt],
[t0].[DocPESUNATDepAmt],
[t0].[PESUNATDepDate],
[t0].[PESUNATDepNum],
[t0].[PESUNATNum],
[t0].[DocPEDetTaxAmt],
[t0].[MXFiscalFolio],
[t0].[PEBOEIsMultiGen],
[t0].[ChangedBy],
[t0].[ChangeDate],
[t0].[PrePayHeadNum],
[t0].[MXRetentionCode],
[t0].[PERefDocID],
[t0].[PEReasonCode],
[t0].[PEReasonDesc],
[t0].[MYImportNum],
[t0].[TWGUIRegNumSeller],
[t0].[TWGUIRegNumBuyer],
[t0].[MXTARCode],
[t0].[GRNIClearing],
[t0].[PEFiscalCreditOperStatus],
[t0].[PEInternatTaxAgr],
[t0].[PERentType],
[t0].[PEPurchaseType],
[t0].[THRefInvoiceNum],
[t0].[THRefVendorNum],
[t0].[JPSummarizationDate],
[t0].[JPBillingDate],
[t0].[JPBillingNumber],
[t0].[SelfInvoice],
[t0].[Printed],
[t0].[PurPoint],
[t0].[PLInvoiceReference],
[t0].[INPortCode],
[t0].[RefCancelledby],
[t0].[CancellationInv],
[t0].[NettingID],
[t0].[WithholdAcctToInterim],
[t0].[APTaxRoundOption],
[t0].[SourcePlant],
[t0].[ExtSysType],
[t0].[ExtSysURL],
[t0].[CHQRIBAN],
[t0].[CHQRReference],
[t0].[EDIInvoice],
CAST(0 AS bit) AS [AllowMultInvcReceipts],
CAST(0 AS bit) AS [ApplyAPPrePayAuto],
'' AS [BankName],
'' AS [BaseCurrencyID],
'' AS [BaseCurrSymbol],
'' AS [BillAddressList],
CAST(0 AS bit) AS [CanChangeTaxLiab],
CAST(0 AS bit) AS [COIFRSCalculation],
CAST(0 AS bit) AS [COIFRSEnabled],
CAST(0.0 AS decimal(20,9)) AS [COIFRSFinancialCharge],
CAST(0.0 AS decimal(20,9)) AS [COIFRSInterestRate],
CAST(0 AS int) AS [COIFRSNumberOfPeriods],
CAST(0.0 AS decimal(20,9)) AS [COIFRSPresentValue],
CAST(0 AS bit) AS [CPayIMReceived],
CAST(0 AS bit) AS [CPayOpenPayable],
CAST(0.0 AS decimal(20,9)) AS [CumulativeBalance],
CAST(0 AS bit) AS [CurrencySwitch],
CAST(0 AS int) AS [CurrInstanceNum],
'' AS [CurrSymbol],
CAST(0 AS bit) AS [DisableAplDate],
CAST(0.0 AS decimal(20,9)) AS [DocCOIFRSFinancialCharge],
CAST(0.0 AS decimal(20,9)) AS [DocCOIFRSPresentValue],
CAST(0.0 AS decimal(20,9)) AS [DocCumulativeBalance],
CAST(0.0 AS decimal(20,9)) AS [DocInvoiceVariance],
CAST(0.0 AS decimal(20,9)) AS [DocMiscChrgNonDeducTax],
CAST(0.0 AS decimal(20,9)) AS [DocMiscChrgVariance],
CAST(0.0 AS decimal(20,9)) AS [DocScrHdrExpTotal],
CAST(0.0 AS decimal(20,9)) AS [DocSourceRecurBalance],
CAST(0.0 AS decimal(20,9)) AS [DspGuiImportTaxBasis],
CAST(0 AS bit) AS [EnableAssignLegNum],
CAST(0 AS bit) AS [EnableCPay],
CAST(0 AS bit) AS [EnableDueDate],
CAST(0 AS bit) AS [EnableExchangeRate],
CAST(0 AS bit) AS [EnableLockRate],
CAST(0 AS bit) AS [EnableTaxExRate],
CAST(0 AS bit) AS [EnableTaxLock],
CAST(0 AS bit) AS [EnableTranDocType],
CAST(0 AS bit) AS [EnableVoidLegNum],
'' AS [ExchangeRateDate],
CAST(0 AS bit) AS [GuiTaxBasisFlag],
CAST(0 AS bit) AS [HasLegNumCnfg],
'' AS [IBANCode],
'' AS [InvoiceTypeDesc],
CAST(0.0 AS decimal(20,9)) AS [InvoiceVariance],
CAST(0 AS bit) AS [IsLatestRecurrence],
CAST(0 AS bit) AS [IsLcked],
CAST(0 AS bit) AS [IsOnlyMiscRecords],
CAST(0 AS bit) AS [LACTaxCalcEnabled],
CAST(0 AS int) AS [LatestInvoice],
'' AS [LatestInvString],
'' AS [LegalNumberMessage],
CAST(0 AS bit) AS [LineOrMscChrgExists],
'' AS [LockStatus],
CAST(0.0 AS decimal(20,9)) AS [MiscChrgNonDeducTax],
CAST(0.0 AS decimal(20,9)) AS [MiscChrgVariance],
null AS [NextInvoiceDate],
CAST(0 AS bit) AS [NoChangeRecur],
'' AS [PayMethod],
'' AS [PEFiscalCreditOperStatusDsp],
CAST(0 AS bit) AS [PEIsNRInvc],
CAST(0 AS bit) AS [PLVendorAutoInvoiceNum],
CAST(0 AS bit) AS [PostInvtyWipCos],
'' AS [RecalcAmts],
CAST(0 AS bit) AS [Recurring],
'' AS [RecurringState],
CAST(0.0 AS decimal(20,9)) AS [Rpt1COIFRSFinancialCharge],
CAST(0.0 AS decimal(20,9)) AS [Rpt1COIFRSPresentValue],
CAST(0.0 AS decimal(20,9)) AS [Rpt1CumulativeBalance],
CAST(0.0 AS decimal(20,9)) AS [Rpt1InvoiceVariance],
CAST(0.0 AS decimal(20,9)) AS [Rpt1MiscChrgNonDeducTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt1MiscChrgVariance],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrDiscountAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrHdrExpTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrHdrMiscChrgTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrInvLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrInvoiceVendorAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrLACTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrRounding],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotBOEWithholding],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotSelfAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrTotWithholdingAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt1ScrUnpostedBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt1SourceRecurBalance],
CAST(0.0 AS decimal(20,9)) AS [Rpt2COIFRSFinancialCharge],
CAST(0.0 AS decimal(20,9)) AS [Rpt2COIFRSPresentValue],
CAST(0.0 AS decimal(20,9)) AS [Rpt2CumulativeBalance],
CAST(0.0 AS decimal(20,9)) AS [Rpt2InvoiceVariance],
CAST(0.0 AS decimal(20,9)) AS [Rpt2MiscChrgNonDeducTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt2MiscChrgVariance],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrDiscountAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrHdrExpTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrHdrMiscChrgTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrInvLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrInvoiceVendorAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrLACTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrRounding],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotBOEWithholding],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotSelfAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrTotWithholdingAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt2ScrUnpostedBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt2SourceRecurBalance],
CAST(0.0 AS decimal(20,9)) AS [Rpt3COIFRSFinancialCharge],
CAST(0.0 AS decimal(20,9)) AS [Rpt3COIFRSPresentValue],
CAST(0.0 AS decimal(20,9)) AS [Rpt3CumulativeBalance],
CAST(0.0 AS decimal(20,9)) AS [Rpt3InvoiceVariance],
CAST(0.0 AS decimal(20,9)) AS [Rpt3MiscChrgNonDeducTax],
CAST(0.0 AS decimal(20,9)) AS [Rpt3MiscChrgVariance],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrDiscountAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrHdrExpTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrHdrMiscChrgTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrInvLineTotal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrInvoiceVendorAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrLACTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrRounding],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotBOEWithholding],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotSelfAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrTotWithholdingAmt],
CAST(0.0 AS decimal(20,9)) AS [Rpt3ScrUnpostedBal],
CAST(0.0 AS decimal(20,9)) AS [Rpt3SourceRecurBalance],
CAST(0.0 AS decimal(20,9)) AS [RptScrTotWithholdingAmt],
CAST(0 AS int) AS [RvnJrnUID],
CAST(0.0 AS decimal(20,9)) AS [ScrDiscountAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocDiscountAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocHdrMiscChrgTotal],
CAST(0.0 AS decimal(20,9)) AS [ScrDocInvLineTotal],
CAST(0.0 AS decimal(20,9)) AS [ScrDocInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocInvoiceBal],
CAST(0.0 AS decimal(20,9)) AS [ScrDocInvoiceVendorAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocRounding],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotBOEWithholding],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotSelfAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocTotWithholdingAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrDocUnpostedBal],
CAST(0.0 AS decimal(20,9)) AS [ScrHdrExpTotal],
CAST(0.0 AS decimal(20,9)) AS [ScrHdrMiscChrgTotal],
CAST(0.0 AS decimal(20,9)) AS [ScrInvLineTotal],
CAST(0.0 AS decimal(20,9)) AS [ScrInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrInvoiceBal],
'' AS [ScrInvoiceRef],
CAST(0.0 AS decimal(20,9)) AS [ScrInvoiceVendorAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrLACDocTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrLACTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrRounding],
CAST(0.0 AS decimal(20,9)) AS [ScrTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotBOEWithholding],
CAST(0.0 AS decimal(20,9)) AS [ScrTotDedTaxAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotInvoiceAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotReportableAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotSelfAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotTaxableAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrTotWithholdingAmt],
CAST(0.0 AS decimal(20,9)) AS [ScrUnpostedBal],
CAST(0 AS bit) AS [SkipRecurring],
'' AS [SourceInvoiceNum],
null AS [SourceLastDate],
CAST(0.0 AS decimal(20,9)) AS [SourceRecurBalance],
'' AS [SwiftCode],
'' AS [SystemTranType],
CAST(0.0 AS decimal(20,9)) AS [TaxExchangeRate],
CAST(0 AS bit) AS [TaxLinesExist],
CAST(0 AS bit) AS [TaxRateLinesExist],
CAST(0 AS int) AS [TotalInstanceNum],
'' AS [TranDocTypeDescription],
null AS [TransApplyDate],
CAST(0 AS bit) AS [UseTaxRate],
CAST(0 AS bit) AS [VendorInactive],
CAST(0 AS bit) AS [VendorPayHold],
null AS [VNDateReceived],
'' AS [VNInvoiceType],
'' AS [XRateLabel],
CAST(0 AS bit) AS [AllowChgAfterPrint],
'' AS [FormattedVendorNameAddress],
CAST(0 AS bit) AS [SiteIsLegalEntity],
ISNULL(b1.BitValues, CAST(0 AS int)) AS [BitFlag],
ISNULL([L1].[Description], '') AS [AGCustomsDescription],
ISNULL([L2].[Description], '') AS [AGDestinationDescription],
ISNULL([L3].[Inactive], CAST(0 AS bit)) AS [APInvRecurringCycleInactive],
ISNULL([L3].[Description], '') AS [APInvRecurringCycleDescription],
ISNULL([L4].[Description], '') AS [APLOCIDDescription],
ISNULL([L5].[CurrName], '') AS [CurrencyCodeCurrName],
ISNULL([L5].[CurrSymbol], '') AS [CurrencyCodeCurrSymbol],
ISNULL([L5].[CurrencyID], '') AS [CurrencyCodeCurrencyID],
ISNULL([L5].[CurrDesc], '') AS [CurrencyCodeCurrDesc],
ISNULL([L5].[DocumentDesc], '') AS [CurrencyCodeDocumentDesc],
ISNULL([L6].[Description], '') AS [GLCntrlDescription],
ISNULL([L7].[Description], '') AS [GLCntrlTypeDescription],
ISNULL([L8].[JrnlDescription], '') AS [JournalCodeJrnlDescription],
ISNULL([L9].[Type], CAST(0 AS int)) AS [PayMethodType],
ISNULL([L9].[SummarizePerCustomer], CAST(0 AS bit)) AS [PayMethodSummarizePerCustomer],
ISNULL([L9].[Name], '') AS [PayMethodName],
ISNULL([L10].[Description], '') AS [RateGrpCodeDescription],
ISNULL([L11].[Name], '') AS [SourcePlantName],
ISNULL([L12].[Description], '') AS [TaxRateGrpDescription],
ISNULL([L13].[Description], '') AS [TaxRegionCodeDescription],
ISNULL([L14].[Description], '') AS [TermsCodeDescription],
ISNULL([L14].[TermsType], '') AS [TermsCodeTermsType],
ISNULL([L15].[Name], '') AS [THRefVendorNumName],
ISNULL([L15].[VendorID], '') AS [THRefVendorNumVendorID],
ISNULL([L16].[PMUID], CAST(0 AS int)) AS [VendBankPMUID],
ISNULL([L16].[CardCode], '') AS [VendBankCardCode],
ISNULL([L16].[BankAcctNumber], '') AS [VendBankBankAcctNumber],
ISNULL([L16].[IBANCode], '') AS [VendBankIBANCode],
ISNULL([L16].[BankGiroAcctNbr], '') AS [VendBankBankGiroAcctNbr],
ISNULL([L16].[SwiftNum], '') AS [VendBankSwiftNum],
ISNULL([L16].[LocalBIC], '') AS [VendBankLocalBIC],
ISNULL([L16].[BankName], '') AS [VendBankBankName],
ISNULL([L17].[CurrencyCode], '') AS [VendorNumCurrencyCode],
ISNULL([L17].[ZIP], '') AS [VendorNumZIP],
ISNULL([L17].[Address2], '') AS [VendorNumAddress2],
ISNULL([L17].[Address3], '') AS [VendorNumAddress3],
ISNULL([L17].[City], '') AS [VendorNumCity],
ISNULL([L17].[Address1], '') AS [VendorNumAddress1],
ISNULL([L17].[Country], '') AS [VendorNumCountry],
ISNULL([L17].[VendorID], '') AS [VendorNumVendorID],
ISNULL([L17].[TermsCode], '') AS [VendorNumTermsCode],
ISNULL([L17].[DefaultFOB], '') AS [VendorNumDefaultFOB],
ISNULL([L17].[State], '') AS [VendorNumState],
ISNULL([L17].[Name], '') AS [VendorNumName],
ISNULL([L18].[APTaxLnLevel], CAST(0 AS bit)) AS [XbSystAPTaxLnLevel],
ISNULL([L18].[IsDiscountforDebitM], CAST(0 AS bit)) AS [XbSystIsDiscountforDebitM]
FROM [Erp].[APInvHed] AS [t0]
LEFT JOIN [Ice].[BitFlag] AS b1 ON b1.RelatedToSchemaName=N'Erp' AND b1.RelatedToTable=N'APInvHed' AND b1.RelatedToRowId = t0.SysRowID
LEFT JOIN [Erp].[AGCustoms] AS [L1] ON ([L1].[Company] = [t0].[Company] AND [L1].[CustomsCode] = [t0].[AGCustomsCode])
LEFT JOIN [Erp].[AGDestination] AS [L2] ON ([L2].[Company] = [t0].[Company] AND [L2].[DestinationCode] = [t0].[AGDestinationCode])
LEFT JOIN [Erp].[RecurringCycle] AS [L3] ON ([L3].[Company] = [t0].[Company] AND [L3].[CycleCode] = [t0].[CycleCode])
LEFT JOIN [Erp].[APLOC] AS [L4] ON ([L4].[Company] = [t0].[Company] AND [L4].[LCID] = [t0].[APLOCID])
LEFT JOIN [Erp].[Currency] AS [L5] ON ([L5].[Company] = [t0].[Company] AND [L5].[CurrencyCode] = [t0].[CurrencyCode])
LEFT JOIN [Erp].[GLCntrl] AS [L6] ON ([L6].[Company] = [t0].[Company] AND [L6].[GLControlType] = [t0].[GLControlType] AND [L6].[GLControlCode] = [t0].[GLControlCode])
LEFT JOIN [Erp].[GLCntrlType] AS [L7] ON ([L7].[Company] = [t0].[Company] AND [L7].[GLControlType] = [t0].[GLControlType])
LEFT JOIN [Erp].[JrnlCode] AS [L8] ON ([L8].[Company] = [t0].[Company] AND [L8].[JournalCode] = [t0].[JournalCode])
LEFT JOIN [Erp].[PayMethod] AS [L9] ON ([L9].[Company] = [t0].[Company] AND [L9].[PMUID] = [t0].[PMUID])
LEFT JOIN [Erp].[CurrRateGrp] AS [L10] ON ([L10].[Company] = [t0].[Company] AND [L10].[RateGrpCode] = [t0].[RateGrpCode])
LEFT JOIN [Erp].[Plant] AS [L11] ON ([L11].[Company] = [t0].[Company] AND [L11].[Plant] = [t0].[SourcePlant])
LEFT JOIN [Erp].[CurrRateGrp] AS [L12] ON ([L12].[Company] = [t0].[Company] AND [L12].[RateGrpCode] = [t0].[TaxRateGrpCode])
LEFT JOIN [Erp].[TaxRgn] AS [L13] ON ([L13].[Company] = [t0].[Company] AND [L13].[TaxRegionCode] = [t0].[TaxRegionCode])
LEFT JOIN [Erp].[PurTerms] AS [L14] ON ([L14].[Company] = [t0].[Company] AND [L14].[TermsCode] = [t0].[TermsCode])
LEFT JOIN [Erp].[Vendor] AS [L15] ON ([L15].[Company] = [t0].[Company] AND [L15].[VendorNum] = [t0].[THRefVendorNum])
LEFT JOIN [Erp].[VendBank] AS [L16] ON ([L16].[Company] = [t0].[Company] AND [L16].[VendorNum] = [t0].[VendorNum] AND [L16].[BankID] = [t0].[BankID])
LEFT JOIN [Erp].[Vendor] AS [L17] ON ([L17].[Company] = [t0].[Company] AND [L17].[VendorNum] = [t0].[VendorNum])
LEFT JOIN [Erp].[XbSyst] AS [L18] ON ([L18].[Company] = [t0].[Company])
	WHERE [t0].SysRowID = @SysRowID
END
