//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.BO.IssueReturn.Resources
{
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class for looking up localized (formatted) strings.
    ///This is a Server Side Strings Resource File. It may contain only string entries.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Ice.Explorer.SingleFileGenerators.StringsDesignerGenerator", "4.2.100.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Strings : Ice.Resources.StringsBase<Erp.BO.IssueReturn.Resources.Strings>
    {
        
        protected Strings()
        {
        }
        
        /// <summary>
        /// String: 'Error creating PartTran.'.
        /// </summary>
        internal static string ErrorCreatingPartTran
        {
            get
            {
                return GetString("ErrorCreatingPartTran");
            }
        }
        
        /// <summary>
        /// String: 'Query: [{0}] is invalid.'.
        /// </summary>
        internal static string QueryIsInvalid(object arg0)
        {
            return GetString("QueryIsInvalid", arg0);
        }
        
        /// <summary>
        /// String: 'Query: [{0}] cannot be opened.'.
        /// </summary>
        internal static string QueryCannotBeOpened(object arg0)
        {
            return GetString("QueryCannotBeOpened", arg0);
        }
        
        /// <summary>
        /// String: 'A valid MtlQueue RowIdent is required.'.
        /// </summary>
        internal static string AValidMtlQuRowIdIsRequi
        {
            get
            {
                return GetString("AValidMtlQuRowIdIsRequi");
            }
        }
        
        /// <summary>
        /// String: 'Program error. Visible flag = no. Should not have allowed selection.'.
        /// </summary>
        internal static string ProgramErrorVisibleFlagNoShouldNotHaveAllowedSelec
        {
            get
            {
                return GetString("ProgramErrorVisibleFlagNoShouldNotHaveAllowedSelec");
            }
        }
        
        /// <summary>
        /// String: 'A valid trantype is required.'.
        /// </summary>
        internal static string AValidTrantypeIsRequired
        {
            get
            {
                return GetString("AValidTrantypeIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'A valid TranType is required.  Cannot determine the Direction of the Job from the TranType.'.
        /// </summary>
        internal static string AValidTranTIsRequiCannotDeterTheDirecOfTheJobFrom
        {
            get
            {
                return GetString("AValidTranTIsRequiCannotDeterTheDirecOfTheJobFrom");
            }
        }
        
        /// <summary>
        /// String: 'IssueReturn record not found.'.
        /// </summary>
        internal static string IssueReturnRecordNotFound
        {
            get
            {
                return GetString("IssueReturnRecordNotFound");
            }
        }
        
        /// <summary>
        /// String: 'Serial Numbers are not required for this transaction.'.
        /// </summary>
        internal static string SerialNumbersAreNotRequiForThisTrans
        {
            get
            {
                return GetString("SerialNumbersAreNotRequiForThisTrans");
            }
        }
        
        /// <summary>
        /// String: 'Part record not found.'.
        /// </summary>
        internal static string PartRecordNotFound
        {
            get
            {
                return GetString("PartRecordNotFound");
            }
        }
        
        /// <summary>
        /// String: 'The part you are issuing is a backflushed part.  Duplicate materials could be issued if the Backflush box is checked in Job Closing when the job is completed or closed.'.
        /// </summary>
        internal static string ThePartYouAreIssuingIsABackfPartDupliMaterCould
        {
            get
            {
                return GetString("ThePartYouAreIssuingIsABackfPartDupliMaterCould");
            }
        }
        
        /// <summary>
        /// String: 'A valid Assembly is required.'.
        /// </summary>
        internal static string AValidAssemblyIsRequired
        {
            get
            {
                return GetString("AValidAssemblyIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'This Job has not been released. Entry not allowed.'.
        /// </summary>
        internal static string ThisJobHasNotBeenReleaEntryNotAllowed
        {
            get
            {
                return GetString("ThisJobHasNotBeenReleaEntryNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'This Job has been closed. Entry not allowed.'.
        /// </summary>
        internal static string ThisJobHasBeenClosedEntryNotAllowed
        {
            get
            {
                return GetString("ThisJobHasBeenClosedEntryNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'Job not found.'.
        /// </summary>
        internal static string JobNotFound
        {
            get
            {
                return GetString("JobNotFound");
            }
        }
        
        /// <summary>
        /// String: 'A valid From Job Number is required.'.
        /// </summary>
        internal static string AValidFromJobNumberIsRequired
        {
            get
            {
                return GetString("AValidFromJobNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'A valid To Job Number is required.'.
        /// </summary>
        internal static string AValidToJobNumberIsRequired
        {
            get
            {
                return GetString("AValidToJobNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Serial number(s) have already been selected for bin {0}. They will be deselected. Do you wish to continue?'.
        /// </summary>
        internal static string SerialNumberSHaveAlreadyBeenSelecForBinDoYouWish(object arg0)
        {
            return GetString("SerialNumberSHaveAlreadyBeenSelecForBinDoYouWish", arg0);
        }
        
        /// <summary>
        /// String: 'There is no outstanding WIP balance for this material.'.
        /// </summary>
        internal static string ThereIsNoOutstWIPBalanceForThisMater
        {
            get
            {
                return GetString("ThereIsNoOutstWIPBalanceForThisMater");
            }
        }
        
        /// <summary>
        /// String: 'There is no outstanding WIP balance for this operation.'.
        /// </summary>
        internal static string ThereIsNoOutstWIPBalanceForThisOpera
        {
            get
            {
                return GetString("ThereIsNoOutstWIPBalanceForThisOpera");
            }
        }
        
        /// <summary>
        /// String: 'A valid Job material is required.'.
        /// </summary>
        internal static string AValidJobMaterialIsRequired
        {
            get
            {
                return GetString("AValidJobMaterialIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Bin: {0} is inactive'.
        /// </summary>
        internal static string BinIsInactive(object arg0)
        {
            return GetString("BinIsInactive", arg0);
        }
        
        /// <summary>
        /// String: 'This transaction will result into a negative FIFO onhand quantity.  Transaction not allowed.'.
        /// </summary>
        internal static string ThisTransWillResultIntoANegatFIFOOnhandQuantTrans
        {
            get
            {
                return GetString("ThisTransWillResultIntoANegatFIFOOnhandQuantTrans");
            }
        }
        
        /// <summary>
        /// String: '{0} transaction type is not handled by IssueReturn business process.'.
        /// </summary>
        internal static string TransTypeIsNotHandledByIssueBusinProcess(object arg0)
        {
            return GetString("TransTypeIsNotHandledByIssueBusinProcess", arg0);
        }
        
        /// <summary>
        /// String: 'Quantity available to move has been reduced to {0}.'.
        /// </summary>
        internal static string QuantAvailToMoveHasBeenReducedTo(object arg0)
        {
            return GetString("QuantAvailToMoveHasBeenReducedTo", arg0);
        }
        
        /// <summary>
        /// String: 'A valid part number is required.'.
        /// </summary>
        internal static string AValidPartNumberIsRequired
        {
            get
            {
                return GetString("AValidPartNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Invalid UOM for Part Number.'.
        /// </summary>
        internal static string InvalidUOMForPartNumber
        {
            get
            {
                return GetString("InvalidUOMForPartNumber");
            }
        }
        
        /// <summary>
        /// String: 'Invalid To Warehouse.'.
        /// </summary>
        internal static string InvalidToWarehouse
        {
            get
            {
                return GetString("InvalidToWarehouse");
            }
        }
        
        /// <summary>
        /// String: 'A valid Job number is required.'.
        /// </summary>
        internal static string AValidJobNumberIsRequired
        {
            get
            {
                return GetString("AValidJobNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Jobs material information is not on file, cannot issue.'.
        /// </summary>
        internal static string JobsMaterInforIsNotOnFileCannotIssue
        {
            get
            {
                return GetString("JobsMaterInforIsNotOnFileCannotIssue");
            }
        }
        
        /// <summary>
        /// String: 'From job number information is not on file, cannot issue.'.
        /// </summary>
        internal static string FromJobNumberInforIsNotOnFileCannotIssue
        {
            get
            {
                return GetString("FromJobNumberInforIsNotOnFileCannotIssue");
            }
        }
        
        /// <summary>
        /// String: 'Invalid From Warehouse.'.
        /// </summary>
        internal static string InvalidFromWarehouse
        {
            get
            {
                return GetString("InvalidFromWarehouse");
            }
        }
        
        /// <summary>
        /// String: 'A valid Job Assembly is required.'.
        /// </summary>
        internal static string AValidJobAssemblyIsRequired
        {
            get
            {
                return GetString("AValidJobAssemblyIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Cannot perform STK-MTL transaction to a managed bin.'.
        /// </summary>
        internal static string CannotPerformSTKMTLTransToAManagedBin
        {
            get
            {
                return GetString("CannotPerformSTKMTLTransToAManagedBin");
            }
        }
        
        /// <summary>
        /// String: 'Cannot perform STK-UKN transaction to a managed bin.'.
        /// </summary>
        internal static string CannotPerformSTKUKNTransToAManagedBin
        {
            get
            {
                return GetString("CannotPerformSTKUKNTransToAManagedBin");
            }
        }
        
        /// <summary>
        /// String: 'Could not create serial number {0}.'.
        /// </summary>
        internal static string CouldNotCreateSerialNumber(object arg0)
        {
            return GetString("CouldNotCreateSerialNumber", arg0);
        }
        
        /// <summary>
        /// String: 'A valid {0} Assembly is required.'.
        /// </summary>
        internal static string AValidAssemblyIsRequired_0(object arg0)
        {
            return GetString("AValidAssemblyIsRequired_0", arg0);
        }
        
        /// <summary>
        /// String: 'A valid {0} Job Number is required.'.
        /// </summary>
        internal static string AValidJobNumberIsRequired_0(object arg0)
        {
            return GetString("AValidJobNumberIsRequired_0", arg0);
        }
        
        /// <summary>
        /// String: '{0} Job has not been released, cannot issue.'.
        /// </summary>
        internal static string JobHasNotBeenReleaCannotIssue(object arg0)
        {
            return GetString("JobHasNotBeenReleaCannotIssue", arg0);
        }
        
        /// <summary>
        /// String: '{0} Job has been closed, cannot issue.'.
        /// </summary>
        internal static string JobHasBeenClosedCannotIssue(object arg0)
        {
            return GetString("JobHasBeenClosedCannotIssue", arg0);
        }
        
        /// <summary>
        /// String: 'A valid Service Call Job Number is required.'.
        /// </summary>
        internal static string AValidServiceCallJobNumberIsRequi
        {
            get
            {
                return GetString("AValidServiceCallJobNumberIsRequi");
            }
        }
        
        /// <summary>
        /// String: 'The Service Call has been invoiced, cannot issue.'.
        /// </summary>
        internal static string TheServiceCallHasBeenInvoiCannotIssue
        {
            get
            {
                return GetString("TheServiceCallHasBeenInvoiCannotIssue");
            }
        }
        
        /// <summary>
        /// String: 'The job does not have any assemblies.'.
        /// </summary>
        internal static string TheJobDoNotHaveAnyAssembly
        {
            get
            {
                return GetString("TheJobDoNotHaveAnyAssembly");
            }
        }
        
        /// <summary>
        /// String: 'Material is a job miscellaneous charge, cannot issue.'.
        /// </summary>
        internal static string MaterIsAJobMisceChargeCannotIssue
        {
            get
            {
                return GetString("MaterIsAJobMisceChargeCannotIssue");
            }
        }
        
        /// <summary>
        /// String: 'A valid Job Operation is required.'.
        /// </summary>
        internal static string AValidJobOperationIsRequired
        {
            get
            {
                return GetString("AValidJobOperationIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'A Lot number is required.'.
        /// </summary>
        internal static string ALotNumberIsRequired
        {
            get
            {
                return GetString("ALotNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'A valid Lot number is required.'.
        /// </summary>
        internal static string AValidLotNumberIsRequired
        {
            get
            {
                return GetString("AValidLotNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'The Part does not require a Lot number.'.
        /// </summary>
        internal static string ThePartDoesNotRequireALotNumber
        {
            get
            {
                return GetString("ThePartDoesNotRequireALotNumber");
            }
        }
        
        /// <summary>
        /// String: 'A valid Part number is required.'.
        /// </summary>
        internal static string AValidPartNumberIsRequired_0
        {
            get
            {
                return GetString("AValidPartNumberIsRequired_0");
            }
        }
        
        /// <summary>
        /// String: 'Part {0} is inactive.'.
        /// </summary>
        internal static string PartIsInactive(object arg0)
        {
            return GetString("PartIsInactive", arg0);
        }
        
        /// <summary>
        /// String: 'The part has not been issued to the job.'.
        /// </summary>
        internal static string ThePartHasNotBeenIssuedToTheJob
        {
            get
            {
                return GetString("ThePartHasNotBeenIssuedToTheJob");
            }
        }
        
        /// <summary>
        /// String: 'The part number cannot be changed.'.
        /// </summary>
        internal static string ThePartNumberCannotBeChanged
        {
            get
            {
                return GetString("ThePartNumberCannotBeChanged");
            }
        }
        
        /// <summary>
        /// String: 'A Part tracking record does not exist for the given From values.'.
        /// </summary>
        internal static string APartTrackRecordDoesNotExistForTheGivenFromValues
        {
            get
            {
                return GetString("APartTrackRecordDoesNotExistForTheGivenFromValues");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is voided.'.
        /// </summary>
        internal static string ThisSerialNumberIsVoided
        {
            get
            {
                return GetString("ThisSerialNumberIsVoided");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is scrapped.'.
        /// </summary>
        internal static string ThisSerialNumberIsScrapped
        {
            get
            {
                return GetString("ThisSerialNumberIsScrapped");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not have the status of Inventory.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotHaveTheStatusOfInven
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotHaveTheStatusOfInven");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not exist in inventory at this warehouse.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotExistInInvenAtThisWareh
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotExistInInvenAtThisWareh");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not exist in inventory in this bin.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotExistInInvenInThisBin
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotExistInInvenInThisBin");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not exist.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotExist
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotExist");
            }
        }
        
        /// <summary>
        /// String: 'This serial number already exists in inventory.'.
        /// </summary>
        internal static string ThisSerialNumberAlreadyExistsInInven
        {
            get
            {
                return GetString("ThisSerialNumberAlreadyExistsInInven");
            }
        }
        
        /// <summary>
        /// String: 'Existing serial number must be flagged as Voided to be valid for selection.'.
        /// </summary>
        internal static string ExistSerialNumberMustBeFlaggedAsVoidedToBeValid
        {
            get
            {
                return GetString("ExistSerialNumberMustBeFlaggedAsVoidedToBeValid");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not have the status of WIP or CONSUMED.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotHaveTheStatusOfWIPOrCONSU
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotHaveTheStatusOfWIPOrCONSU");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is not issued to this job/assembly.'.
        /// </summary>
        internal static string ThisSerialNumberIsNotIssuedToThisJobAssem
        {
            get
            {
                return GetString("ThisSerialNumberIsNotIssuedToThisJobAssem");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not have the status of MISC-ISSUE.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotHaveTheStatusOfMISCISSUE
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotHaveTheStatusOfMISCISSUE");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is not issued to this job/assembly/Mtl.'.
        /// </summary>
        internal static string ThisSerialNumberIsNotIssuedToThisJobAssemMtl
        {
            get
            {
                return GetString("ThisSerialNumberIsNotIssuedToThisJobAssemMtl");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not exist at this warehouse.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotExistAtThisWareh
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotExistAtThisWareh");
            }
        }
        
        /// <summary>
        /// String: 'Cannot move Serial Number:{0}. Has invalid status: {1}, this transaction requires status {2}.'.
        /// </summary>
        internal static string CannotMoveSerialNumberHasInvalidStatusThisTrans(object arg0, object arg1, object arg2)
        {
            return GetString("CannotMoveSerialNumberHasInvalidStatusThisTrans", arg0, arg1, arg2);
        }
        
        /// <summary>
        /// String: 'This Serial Number was not selected for the disposition for this Material Queue record.'.
        /// </summary>
        internal static string ThisSerialNumberWasNotSelecForTheDispoForThisMater
        {
            get
            {
                return GetString("ThisSerialNumberWasNotSelecForTheDispoForThisMater");
            }
        }
        
        /// <summary>
        /// String: 'ttIssueReturn record not found.'.
        /// </summary>
        internal static string TtIssueReturnRecordNotFound
        {
            get
            {
                return GetString("TtIssueReturnRecordNotFound");
            }
        }
        
        /// <summary>
        /// String: 'A valid quantity is required.'.
        /// </summary>
        internal static string AValidQuantityIsRequired
        {
            get
            {
                return GetString("AValidQuantityIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Quantity cannot be negative.'.
        /// </summary>
        internal static string QuantityCannotBeNegative
        {
            get
            {
                return GetString("QuantityCannotBeNegative");
            }
        }
        
        /// <summary>
        /// String: 'Cannot return more than was issued.'.
        /// </summary>
        internal static string CannotReturnMoreThanWasIssued
        {
            get
            {
                return GetString("CannotReturnMoreThanWasIssued");
            }
        }
        
        /// <summary>
        /// String: 'To Warehouse cannot be set without Advanced Material Management License.'.
        /// </summary>
        internal static string ToWarehCannotBeSetWithoutAdvanMaterManagLicense
        {
            get
            {
                return GetString("ToWarehCannotBeSetWithoutAdvanMaterManagLicense");
            }
        }
        
        /// <summary>
        /// String: 'To Bin cannot be set without Advanced Material Management License.'.
        /// </summary>
        internal static string ToBinCannotBeSetWithoutAdvanMaterManagLicense
        {
            get
            {
                return GetString("ToBinCannotBeSetWithoutAdvanMaterManagLicense");
            }
        }
        
        /// <summary>
        /// String: 'From Warehouse cannot be set without Advanced Material Management License.'.
        /// </summary>
        internal static string FromWarehCannotBeSetWithoutAdvanMaterManagLicense
        {
            get
            {
                return GetString("FromWarehCannotBeSetWithoutAdvanMaterManagLicense");
            }
        }
        
        /// <summary>
        /// String: 'From Bin cannot be set without Advanced Material Management License.'.
        /// </summary>
        internal static string FromBinCannotBeSetWithoutAdvanMaterManagLicense
        {
            get
            {
                return GetString("FromBinCannotBeSetWithoutAdvanMaterManagLicense");
            }
        }
        
        /// <summary>
        /// String: 'A valid From Warehouse is required.'.
        /// </summary>
        internal static string AValidFromWarehouseIsRequired
        {
            get
            {
                return GetString("AValidFromWarehouseIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'A valid From Bin number is required.'.
        /// </summary>
        internal static string AValidFromBinNumberIsRequired
        {
            get
            {
                return GetString("AValidFromBinNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'The From Bin cannot be a managed bin.'.
        /// </summary>
        internal static string TheFromBinCannotBeAManagedBin
        {
            get
            {
                return GetString("TheFromBinCannotBeAManagedBin");
            }
        }
        
        /// <summary>
        /// String: 'A valid To Warehouse is required.'.
        /// </summary>
        internal static string AValidToWarehouseIsRequired
        {
            get
            {
                return GetString("AValidToWarehouseIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'A valid To Bin number is required.'.
        /// </summary>
        internal static string AValidToBinNumberIsRequired
        {
            get
            {
                return GetString("AValidToBinNumberIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'The To Bin cannot be a managed bin.'.
        /// </summary>
        internal static string TheToBinCannotBeAManagedBin
        {
            get
            {
                return GetString("TheToBinCannotBeAManagedBin");
            }
        }
        
        /// <summary>
        /// String: 'A valid date is required.'.
        /// </summary>
        internal static string AValidDateIsRequired
        {
            get
            {
                return GetString("AValidDateIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Reason code is required.'.
        /// </summary>
        internal static string ReasonCodeIsRequired
        {
            get
            {
                return GetString("ReasonCodeIsRequired");
            }
        }
        
        /// <summary>
        /// String: 'Reason Code references invalid value.'.
        /// </summary>
        internal static string ReasonCodeReferInvalidValue
        {
            get
            {
                return GetString("ReasonCodeReferInvalidValue");
            }
        }
        
        /// <summary>
        /// String: 'Cannot move between supplier and customer managed bins'.
        /// </summary>
        internal static string CannotMoveBetweenSupplAndCustoManagedBins
        {
            get
            {
                return GetString("CannotMoveBetweenSupplAndCustoManagedBins");
            }
        }
        
        /// <summary>
        /// String: 'Both from and to bins must be Supplier managed bins when performing a PUR-SMI transfer'.
        /// </summary>
        internal static string BothFromAndToBinsMustBeSupplManagedBinsWhenPerfo
        {
            get
            {
                return GetString("BothFromAndToBinsMustBeSupplManagedBinsWhenPerfo");
            }
        }
        
        /// <summary>
        /// String: 'Transfering from one supplier managed bin to another must be for the same supplier.'.
        /// </summary>
        internal static string TransFromOneSupplManagedBinToAnotherMustBeForThe
        {
            get
            {
                return GetString("TransFromOneSupplManagedBinToAnotherMustBeForThe");
            }
        }
        
        /// <summary>
        /// String: 'Both from and to bins must be Customer managed bins when performing a PUR-CMI transfer'.
        /// </summary>
        internal static string BothFromAndToBinsMustBeCustoManagedBinsWhenPerfo
        {
            get
            {
                return GetString("BothFromAndToBinsMustBeCustoManagedBinsWhenPerfo");
            }
        }
        
        /// <summary>
        /// String: 'Transfering from one customer managed bin to another must be for the same customer.'.
        /// </summary>
        internal static string TransFromOneCustoManagedBinToAnotherMustBeForThe
        {
            get
            {
                return GetString("TransFromOneCustoManagedBinToAnotherMustBeForThe");
            }
        }
        
        /// <summary>
        /// String: 'Both from and to bins must be Customer managed bins when transfering to or from a customer managed bin'.
        /// </summary>
        internal static string BothFromAndToBinsMustBeCustoManagedBinsWhenTrans
        {
            get
            {
                return GetString("BothFromAndToBinsMustBeCustoManagedBinsWhenTrans");
            }
        }
        
        /// <summary>
        /// String: 'Cannot transfer from a standard bin to a supplier managed bin'.
        /// </summary>
        internal static string CannotTransFromAStandBinToASupplManagedBin
        {
            get
            {
                return GetString("CannotTransFromAStandBinToASupplManagedBin");
            }
        }
        
        /// <summary>
        /// String: 'Cannot transfer from a standard bin to a managed bin'.
        /// </summary>
        internal static string CannotTransFromAStandBinToAManagedBin
        {
            get
            {
                return GetString("CannotTransFromAStandBinToAManagedBin");
            }
        }
        
        /// <summary>
        /// String: 'Record not found.'.
        /// </summary>
        internal static string RecordNotFound
        {
            get
            {
                return GetString("RecordNotFound");
            }
        }
        
        /// <summary>
        /// String: 'for each JobHead{0} no-lock'.
        /// </summary>
        internal static string ForEachJobHeadNoLock(object arg0)
        {
            return GetString("ForEachJobHeadNoLock", arg0);
        }
        
        /// <summary>
        /// String: 'The total quantity ({0} {1}) must be a whole number.'.
        /// </summary>
        internal static string TheTotalQuantMustBeAWholeNumber(object arg0, object arg1)
        {
            return GetString("TheTotalQuantMustBeAWholeNumber", arg0, arg1);
        }
        
        /// <summary>
        /// String: 'Quantity available to move has been reduced to 0.
        ///Request has been deleted.'.
        /// </summary>
        internal static string QuantAvailToMoveHasBeenReducedToRequestHasBeen
        {
            get
            {
                return GetString("QuantAvailToMoveHasBeenReducedToRequestHasBeen");
            }
        }
        
        /// <summary>
        /// String: 'Error encountered when retrieving SN Format.{0}'.
        /// </summary>
        internal static string ErrorEncouWhenRetriSNFormat(object arg0)
        {
            return GetString("ErrorEncouWhenRetriSNFormat", arg0);
        }
        
        /// <summary>
        /// String: 'You cannot issue parts to the top level assembly.'.
        /// </summary>
        internal static string YouCannotIssuePartsToTheTopLevelAssem
        {
            get
            {
                return GetString("YouCannotIssuePartsToTheTopLevelAssem");
            }
        }
        
        /// <summary>
        /// String: 'Quantity cannot be greater than non-conformance quantity'.
        /// </summary>
        internal static string QuantityCannotBeGreaterThanNonConformanceQuantity
        {
            get
            {
                return GetString("QuantityCannotBeGreaterThanNonConformanceQuantity");
            }
        }
        
        /// <summary>
        /// String: 'Invalid quantity after UOM conversion and rounding.'.
        /// </summary>
        internal static string InvalidIssueQty
        {
            get
            {
                return GetString("InvalidIssueQty");
            }
        }
        
        /// <summary>
        /// String: 'Serial number {0} not valid for unpick.'.
        /// </summary>
        internal static string SerialNoNotValidForUnpick(object arg0)
        {
            return GetString("SerialNoNotValidForUnpick", arg0);
        }
        
        /// <summary>
        /// String: 'Bin does not match the Planning Contract Bin. Cannot continue.'.
        /// </summary>
        internal static string PlanContractStop
        {
            get
            {
                return GetString("PlanContractStop");
            }
        }
        
        /// <summary>
        /// String: 'Bin does not match the Planning Contract Bin. Do you wish to continue?'.
        /// </summary>
        internal static string PlanContractWarn
        {
            get
            {
                return GetString("PlanContractWarn");
            }
        }
        
        /// <summary>
        /// String: 'PCID {0} not found.'.
        /// </summary>
        internal static string PCIDNotFound(object arg0)
        {
            return GetString("PCIDNotFound", arg0);
        }
        
        /// <summary>
        /// String: 'Status for PCID {0} is not valid for this transaction.'.
        /// </summary>
        internal static string PCIDStatusInvalid(object arg0)
        {
            return GetString("PCIDStatusInvalid", arg0);
        }
        
        /// <summary>
        /// String: 'Order/Line/Rel {0}: PCID {1} is already being used for a different customer or ship to address.'.
        /// </summary>
        internal static string PCIDCustNoMatch(object arg0, object arg1)
        {
            return GetString("PCIDCustNoMatch", arg0, arg1);
        }
        
        /// <summary>
        /// String: 'Part not found.'.
        /// </summary>
        internal static string PartNotFound
        {
            get
            {
                return GetString("PartNotFound");
            }
        }
        
        /// <summary>
        /// String: 'PCID is required.'.
        /// </summary>
        internal static string PCIDRequired
        {
            get
            {
                return GetString("PCIDRequired");
            }
        }
        
        /// <summary>
        /// String: 'The To Warehouse and Bin does not match the PCID location'.
        /// </summary>
        internal static string PCIDLocationDoesNotMatch
        {
            get
            {
                return GetString("PCIDLocationDoesNotMatch");
            }
        }
        
        /// <summary>
        /// String: 'Bin belongs to a Planning Contract. Cannot continue.'.
        /// </summary>
        internal static string PlanContractOutsideStop
        {
            get
            {
                return GetString("PlanContractOutsideStop");
            }
        }
        
        /// <summary>
        /// String: 'Bin belongs to a Planning Contract. Do you wish to continue?'.
        /// </summary>
        internal static string PlanContractOutsideWarn
        {
            get
            {
                return GetString("PlanContractOutsideWarn");
            }
        }
        
        /// <summary>
        /// String: 'Package Control ID Code {0} is not valid.'.
        /// </summary>
        internal static string PCIDPkgControlIDCodeInvalid(object arg0)
        {
            return GetString("PCIDPkgControlIDCodeInvalid", arg0);
        }
        
        /// <summary>
        /// String: 'Package Control ID Configuration {0} is not dynamic.'.
        /// </summary>
        internal static string PCIDPkgControlIDConfigNotDynamic(object arg0)
        {
            return GetString("PCIDPkgControlIDConfigNotDynamic", arg0);
        }
        
        /// <summary>
        /// String: 'Bin belongs to a different Planning Contract. Cannot continue.'.
        /// </summary>
        internal static string PlanContractOutsideAnotherPCStop
        {
            get
            {
                return GetString("PlanContractOutsideAnotherPCStop");
            }
        }
        
        /// <summary>
        /// String: 'Bin belongs to a different Planning Contract. Do you wish to continue?'.
        /// </summary>
        internal static string PlanContractOutsideAnotherPCWarn
        {
            get
            {
                return GetString("PlanContractOutsideAnotherPCWarn");
            }
        }
        
        /// <summary>
        /// String: 'Mixed Lot Numbers are not allowed by this Package Control ID Configuration.'.
        /// </summary>
        internal static string PCIDMixedLotNumbersNotAllowed
        {
            get
            {
                return GetString("PCIDMixedLotNumbersNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'Mixed Parts are not allowed by this Package Control ID Configuration.'.
        /// </summary>
        internal static string PCIDMixedPartsNotAllowed
        {
            get
            {
                return GetString("PCIDMixedPartsNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'Mixed Units of Measure are not allowed by this Package Control ID Configuration.'.
        /// </summary>
        internal static string PCIDMixedUOMNotAllowed
        {
            get
            {
                return GetString("PCIDMixedUOMNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'Multiple Serial Numbers are not allowed by this Package Control ID Configuration.'.
        /// </summary>
        internal static string PCIDMultipleSerialNumbersNotAllowed
        {
            get
            {
                return GetString("PCIDMultipleSerialNumbersNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'This Order/Line/Release has been picked to multiple PCIDs. PCID must be specified.'.
        /// </summary>
        internal static string PCIDMultipleMatchingPCIDs
        {
            get
            {
                return GetString("PCIDMultipleMatchingPCIDs");
            }
        }
        
        /// <summary>
        /// String: 'PCID status does not allow for unpick.'.
        /// </summary>
        internal static string PCIDInvalidStatus
        {
            get
            {
                return GetString("PCIDInvalidStatus");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is associated with a PCID.'.
        /// </summary>
        internal static string CannotSelectSerialNoWithPCID
        {
            get
            {
                return GetString("CannotSelectSerialNoWithPCID");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is on an open cycle count tag, it cannot be added to a PCID.'.
        /// </summary>
        internal static string CannotSelectSerialOnOpenCycleCount
        {
            get
            {
                return GetString("CannotSelectSerialOnOpenCycleCount");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not exist in this bin.'.
        /// </summary>
        internal static string ThisSerialNumberDoesNotExistInThisBin
        {
            get
            {
                return GetString("ThisSerialNumberDoesNotExistInThisBin");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is for PCID &quot;{0}&quot;.'.
        /// </summary>
        internal static string ThisSerialNumberForPCID(object arg0)
        {
            return GetString("ThisSerialNumberForPCID", arg0);
        }
        
        /// <summary>
        /// String: 'This serial number is not on this PCID.'.
        /// </summary>
        internal static string ThisSerialNumberNotOnPCID
        {
            get
            {
                return GetString("ThisSerialNumberNotOnPCID");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is not on this order release.'.
        /// </summary>
        internal static string ThisSerialNumberNotOnThisOrderRelease
        {
            get
            {
                return GetString("ThisSerialNumberNotOnThisOrderRelease");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not have the status of PICKED.'.
        /// </summary>
        internal static string ThisSerialNumberStatusNotPicked
        {
            get
            {
                return GetString("ThisSerialNumberStatusNotPicked");
            }
        }
        
        /// <summary>
        /// String: 'This serial number does not have the status of PICKED or INVENTORY.'.
        /// </summary>
        internal static string ThisSerialNumberStatusNotPickedOrInventory
        {
            get
            {
                return GetString("ThisSerialNumberStatusNotPickedOrInventory");
            }
        }
        
        /// <summary>
        /// String: 'Transaction Qty will have a value of: {0} The UOM {1} allows zero decimals.'.
        /// </summary>
        internal static string NoDecAllowed(object arg0, object arg1)
        {
            return GetString("NoDecAllowed", arg0, arg1);
        }
        
        /// <summary>
        /// String: 'Not able to move material from/to Time - Backflush Qty Operations'.
        /// </summary>
        internal static string NotAbleToMoveMtlFromToTimeBackflushQtyOperations
        {
            get
            {
                return GetString("NotAbleToMoveMtlFromToTimeBackflushQtyOperations");
            }
        }
        
        /// <summary>
        /// String: 'You cannot issue parts of UOM Class {0} that require UOM Class {1}'.
        /// </summary>
        internal static string CannotChangeUOMClass(object arg0, object arg1)
        {
            return GetString("CannotChangeUOMClass", arg0, arg1);
        }
        
        /// <summary>
        /// String: 'To Warehouse and Bin cannot be changed for this transaction.'.
        /// </summary>
        internal static string FSAToLocationCannotBeChanged
        {
            get
            {
                return GetString("FSAToLocationCannotBeChanged");
            }
        }
        
        /// <summary>
        /// String: 'PCID status must be STOCK for PUR-STK transactions'.
        /// </summary>
        internal static string PCIDStatusMustBeStockForPUR_STK
        {
            get
            {
                return GetString("PCIDStatusMustBeStockForPUR_STK");
            }
        }
        
        /// <summary>
        /// String: 'Package Control is not enabled for this site'.
        /// </summary>
        internal static string PackageControlNotEnabledOnSite
        {
            get
            {
                return GetString("PackageControlNotEnabledOnSite");
            }
        }
        
        /// <summary>
        /// String: 'PCID does not exist'.
        /// </summary>
        internal static string PCIDDoesNotExist
        {
            get
            {
                return GetString("PCIDDoesNotExist");
            }
        }
        
        /// <summary>
        /// String: 'PCID is Staged'.
        /// </summary>
        internal static string PCIDIsStaged
        {
            get
            {
                return GetString("PCIDIsStaged");
            }
        }
        
        /// <summary>
        /// String: 'Part does not exist on the selected PCID.'.
        /// </summary>
        internal static string PartNumIsNotItemPCID
        {
            get
            {
                return GetString("PartNumIsNotItemPCID");
            }
        }
        
        /// <summary>
        /// String: 'The Part Number {0} and Unit of Measure {1} on the selected PCID item is different than is required on the material record.'.
        /// </summary>
        internal static string DifferentPartPCIDQuestion(object arg0, object arg1)
        {
            return GetString("DifferentPartPCIDQuestion", arg0, arg1);
        }
        
        /// <summary>
        /// String: 'There are multiple items in this PCID.  You can manually enter the part information or the PCID can be searched for a specific part. Continue?'.
        /// </summary>
        internal static string MultipleItemsPCIDQuestion
        {
            get
            {
                return GetString("MultipleItemsPCIDQuestion");
            }
        }
        
        /// <summary>
        /// String: 'No match found on the PCID for the Part Num {0} and Unit of measure {1}.'.
        /// </summary>
        internal static string NoMatchFoundOnPCIDForPartAndUM(object arg0, object arg1)
        {
            return GetString("NoMatchFoundOnPCIDForPartAndUM", arg0, arg1);
        }
        
        /// <summary>
        /// String: 'There are multiple items in this PCID.  You can manually enter the part information. Continue?'.
        /// </summary>
        internal static string MultipleItemsPCIDQuestionHH
        {
            get
            {
                return GetString("MultipleItemsPCIDQuestionHH");
            }
        }
        
        /// <summary>
        /// String: 'This Part/Lot/UOM combination does not exist in PCID &quot;{0}&quot;.'.
        /// </summary>
        internal static string ThisPartLotUomCombinationDoesNotExistInPCID(object arg0)
        {
            return GetString("ThisPartLotUomCombinationDoesNotExistInPCID", arg0);
        }
        
        /// <summary>
        /// String: 'Continue?'.
        /// </summary>
        internal static string Continue
        {
            get
            {
                return GetString("Continue");
            }
        }
        
        /// <summary>
        /// String: 'This serial number must match the issue from lot number for a PCID issue.'.
        /// </summary>
        internal static string SerialLotNumMustMatchIssueFromLotForPCID
        {
            get
            {
                return GetString("SerialLotNumMustMatchIssueFromLotForPCID");
            }
        }
        
        /// <summary>
        /// String: 'Only voided or new serial numbers are valid selections for this transaction.'.
        /// </summary>
        internal static string OnlyVoidedOrNewSerialNumbersAllowed
        {
            get
            {
                return GetString("OnlyVoidedOrNewSerialNumbersAllowed");
            }
        }
        
        /// <summary>
        /// String: 'The serial number does not exist in inventory for this lot.'.
        /// </summary>
        internal static string TheSerialNumberDoesNotExistsInThisLot
        {
            get
            {
                return GetString("TheSerialNumberDoesNotExistsInThisLot");
            }
        }
        
        /// <summary>
        /// String: 'This serial number is not voided.'.
        /// </summary>
        internal static string ThisSerialNumberIsNotVoided
        {
            get
            {
                return GetString("ThisSerialNumberIsNotVoided");
            }
        }
        
        /// <summary>
        /// String: 'Tariff (commodity) code should be set on a part.'.
        /// </summary>
        internal static string TariffCodeShouldBeSetOnPart
        {
            get
            {
                return GetString("TariffCodeShouldBeSetOnPart");
            }
        }
        
        /// <summary>
        /// String: 'PCID To Site does not match with Transfer order To Site'.
        /// </summary>
        internal static string PCIDToSiteDoesNotMatchTFOrderToSite
        {
            get
            {
                return GetString("PCIDToSiteDoesNotMatchTFOrderToSite");
            }
        }
        
        /// <summary>
        /// String: 'Returnable PCIDs are not allowed for transfer picking.'.
        /// </summary>
        internal static string ReturnablePCIDNotAllowed
        {
            get
            {
                return GetString("ReturnablePCIDNotAllowed");
            }
        }
        
        /// <summary>
        /// String: 'PCID &apos;{0}&apos; will result in orders with different ERS Order settings within the same PCID.'.
        /// </summary>
        internal static string PCIDOrderNumHasInvalidERSOrder(object arg0)
        {
            return GetString("PCIDOrderNumHasInvalidERSOrder", arg0);
        }
        
        /// <summary>
        /// String: 'TFO Receipt move PCID '.
        /// </summary>
        internal static string TransferOrderReceiptChangePICDLocation
        {
            get
            {
                return GetString("TransferOrderReceiptChangePICDLocation");
            }
        }
        
        /// <summary>
        /// String: 'Transfer to the new bin failed for PCID {0}. Use Inventory Transfer to execute the move manually.'.
        /// </summary>
        internal static string PCIDInventoryTransferFailed(object arg0)
        {
            return GetString("PCIDInventoryTransferFailed", arg0);
        }
        
        /// <summary>
        /// String: 'Attribute Set cannot be changed for Buy to Order part.'.
        /// </summary>
        internal static string BTOAttribute
        {
            get
            {
                return GetString("BTOAttribute");
            }
        }
        
        /// <summary>
        /// String: 'Cannot move more than currently exists in WIP in this location.'.
        /// </summary>
        internal static string CannotMoveMoreThanCurrentlyExistsInThisLocation
        {
            get
            {
                return GetString("CannotMoveMoreThanCurrentlyExistsInThisLocation");
            }
        }
        
        /// <summary>
        /// String: 'Cannot move PCID {0} which already contains WIP with this transaction.  Must execute a separate Move WIP PCID transaction.'.
        /// </summary>
        internal static string CannotMovePCIDAlreadyContainingWIP(object arg0)
        {
            return GetString("CannotMovePCIDAlreadyContainingWIP", arg0);
        }
        
        /// <summary>
        /// String: 'WIP exists for this job/assembly in a PCID.  Unable to process this transaction using the classic UI.'.
        /// </summary>
        internal static string WIPExistsInAPCIDCannotUseClassicUI
        {
            get
            {
                return GetString("WIPExistsInAPCIDCannotUseClassicUI");
            }
        }
        
        /// <summary>
        /// String: 'Cannot move more than was issued to this PCID &apos;{0}&apos;.'.
        /// </summary>
        internal static string CannotMoveMoreThanWasIssuedToThisPCID(object arg0)
        {
            return GetString("CannotMoveMoreThanWasIssuedToThisPCID", arg0);
        }
        
        /// <summary>
        /// String: 'PCID {0} contains at least one Child PCID.  Nested PCIDs are not supported with WIP.  Cannot move PCID {0}.'.
        /// </summary>
        internal static string ChildPCIDsNotSupportedWithWIP(object arg0)
        {
            return GetString("ChildPCIDsNotSupportedWithWIP", arg0);
        }
        
        /// <summary>
        /// String: 'This serial number is for job &apos;{0}&apos;.'.
        /// </summary>
        internal static string ThisSerialNumberForJob(object arg0)
        {
            return GetString("ThisSerialNumberForJob", arg0);
        }
    }
}
